import * as stylex from "@stylexjs/stylex";
import {
	color,
	font,
	radius,
} from "../../../../design-system/styles.stylex.ts";
export const styles = stylex.create({
	resourceCategories: { display: "flex", flexWrap: "wrap", gap: 8 },
	resourceCard: { padding: 24, gap: 12, minHeight: 210, borderRadius: 16 },
	resourcePreview: {
		color: color.textSoft,
		fontSize: font.size_3,
		lineHeight: 1.7,
		margin: 0,
		overflow: "hidden",
		display: "-webkit-box",
		WebkitLineClamp: 4,
		WebkitBoxOrient: "vertical",
	},
	resourceEmpty: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		minHeight: 320,
		padding: 40,
		textAlign: "center",
		color: color.textMuted,
		borderWidth: 1,
		borderStyle: "dashed",
		borderColor: color.borderSubtle,
		borderRadius: 16,
		gap: 12,
	},

	libraryToolbar: {
		display: "flex",
		alignItems: "center",
		gap: 16,
		width: "100%",
		paddingBottom: 16,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.borderSubtle,
	},
	librarySearch: {
		display: "flex",
		alignItems: "center",
		gap: 8,
		flex: 1,
		minWidth: 0,
		color: color.textMuted,
	},
	libraryGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(auto-fill, minmax(min(100%, 280px), 1fr))",
		gap: 16,
		width: "100%",
	},
	libraryCardTitle: {
		backgroundColor: "transparent",
		borderWidth: 0,
		padding: 0,
		color: color.textMain,
		fontSize: 16,
		fontWeight: 600,
		textAlign: "left",
		cursor: "pointer",
	},

	automationMain: { padding: 0, gap: 0, overflow: "hidden" },
	automationSearch: {
		display: "flex",
		alignItems: "center",
		gap: 8,
		padding: 14,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.borderSubtle,
	},
	automationSearchInput: {
		width: "100%",
		minWidth: 0,
		borderWidth: 0,
		backgroundColor: color.transparent,
		color: color.textMain,
		fontSize: font.size_3,
		padding: 4,
	},

	editorTop: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 24,
	},
	editorTitle: {
		flex: 1,
		minWidth: 0,
		borderWidth: 0,
		backgroundColor: color.transparent,
		color: color.textMain,
		fontSize: 24,
		fontWeight: 600,
		letterSpacing: "-0.025em",
		padding: 0,
		outlineOffset: 6,
	},
	editorMeta: {
		display: "flex",
		alignItems: "center",
		gap: 16,
		paddingBottom: 24,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.borderSubtle,
	},
	editorSection: {
		display: "flex",
		flexDirection: "column",
		gap: 16,
		marginTop: 12,
	},
	editorLabel: {
		color: color.textMuted,
		fontSize: font.size_3,
		fontWeight: 500,
	},
	inlineControl: {
		borderWidth: 0,
		borderRadius: radius.md,
		backgroundColor: color.controlHover,
		color: color.textSoft,
		paddingBlock: 7,
		paddingInline: 10,
		fontSize: font.size_3,
		maxWidth: 200,
		minWidth: 0,
	},
	settingRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 16,
		padding: 16,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderSubtle,
		borderRadius: radius.md,
	},
	instructionComposer: {
		display: "flex",
		flexDirection: "column",
		position: "relative",
		borderRadius: 12,
		overflow: "visible",
	},
	instructionInput: {
		width: "100%",
		minHeight: 180,
		boxSizing: "border-box",
		padding: 16,
		borderWidth: 0,
		outline: "none",
		color: color.textMain,
		backgroundColor: color.transparent,
		fontSize: font.size_3,
		lineHeight: 1.7,
		resize: "vertical",
	},
	composerControls: {
		position: "relative",
		display: "flex",
		flexWrap: "wrap",
		gap: 6,
		padding: 10,
	},

	automationWorkspace: {
		display: "grid",
		gridTemplateColumns: {
			default: "230px minmax(0, 1fr)",
			"@media (max-width: 1050px)": "180px minmax(0, 1fr)",
		},
		width: "100%",
		minHeight: 0,
		flex: 1,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: color.borderSubtle,
	},
	automationList: {
		display: "flex",
		flexDirection: "column",
		gap: 12,
		padding: 0,
		borderRightWidth: 1,
		borderRightStyle: "solid",
		borderRightColor: color.borderSubtle,
		overflowY: "auto",
	},
	automationListItem: {
		display: "flex",
		flexDirection: "column",
		gap: 8,
		padding: 12,
		textAlign: "left",
		color: color.textMain,
		borderRadius: radius.md,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	automationContent: {
		display: "flex",
		flexDirection: "column",
		gap: 20,
		paddingBlock: 32,
		paddingInline: "clamp(24px, 4vw, 72px)",
		width: "100%",
		maxWidth: 1240,
		marginInline: "auto",
		boxSizing: "border-box",
		overflowY: "auto",
		minWidth: 0,
	},
	starterGrid: {
		display: "grid",
		gridTemplateColumns: {
			default: "repeat(2, minmax(0, 1fr))",
			"@media (max-width: 1100px)": "1fr",
		},
		gap: 14,
	},
	starterCard: {
		display: "flex",
		flexDirection: "column",
		gap: 12,
		padding: 22,
		minHeight: 170,
		textAlign: "left",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderSubtle,
		borderRadius: radius.md,
		color: color.textMain,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	taskSummary: {
		whiteSpace: "pre-wrap",
		lineHeight: 1.7,
		color: color.textSoft,
	},

	automationForm: {
		display: "flex",
		flexDirection: "column",
		gap: 24,
		padding: 0,
		fontSize: font.size_3,
	},
	compactCode: { minHeight: 80, maxHeight: 180 },
	scheduleSection: {
		display: "flex",
		flexDirection: "column",
		gap: 12,
		paddingTop: 18,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: color.borderSubtle,
	},
	automationSettings: {
		display: "flex",
		flexDirection: "column",
		gap: 14,
		padding: 16,
		borderRadius: radius.md,
		backgroundColor: color.surfaceWhite02,
	},

	repositoryNavList: {
		paddingLeft: 14,
		maxHeight: 240,
		overflowY: "auto",
		flexShrink: 0,
	},
	repositoryNavLabel: {
		flex: 1,
		minWidth: 0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	repositoryWorkspace: {
		display: "flex",
		flexDirection: "column",
		width: "100%",
		height: "100%",
		minWidth: 0,
		minHeight: 0,
	},
	repositoryWorkbench: {
		display: "flex",
		flex: 1,
		minHeight: 0,
		minWidth: 0,
		overflow: "hidden",
	},
	repositoryGraph: {
		display: "flex",
		flex: 1,
		minWidth: 0,
		minHeight: 0,
		overflow: "hidden",
	},
	hidden: { display: "none" },
	repositoryChoices: {
		borderWidth: 0,
		padding: 0,
		margin: 0,
		minWidth: 0,
		display: "flex",
		flexDirection: "column",
		gap: 12,
	},
	repositoryChoiceList: {
		display: "flex",
		flexDirection: "column",
		gap: 12,
		maxHeight: 200,
		overflowY: "auto",
	},
	tab: {
		display: "flex",
		alignItems: "center",
		gap: 10,
		width: "100%",
		height: 29,
		paddingInline: 8,
		borderRadius: radius.md,
		textAlign: "left",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		color: { default: color.textMuted, ":hover": color.textMain },
		fontSize: font.size_3,
		flexShrink: 0,
	},
	mainNavigationItem: { fontWeight: 600 },
	selectedTab: { backgroundColor: color.controlActive, color: color.textMain },
	navigation: {
		maxHeight: "60%",
		overflowY: "auto",
		minHeight: 0,
		display: "flex",
		flexDirection: "column",
		gap: 2,
		padding: 8,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.borderSubtle,
		flexShrink: 0,
	},
	sectionLabel: {
		fontSize: 10,
		fontWeight: 500,
		letterSpacing: "0.06em",
		color: color.textFaint,
		marginBottom: 6,
	},
	heading: {
		width: "100%",
		boxSizing: "border-box",
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 16,
		marginBottom: 12,
	},
	list: {
		width: "100%",
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: color.borderSubtle,
	},
	projectRow: {
		display: "flex",
		alignItems: "center",
		gap: 14,
		minHeight: 60,
		padding: 16,
		textAlign: "left",
		color: color.textSoft,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.borderSubtle,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	listText: {
		display: "flex",
		flexDirection: "column",
		gap: 5,
		flex: 1,
		minWidth: 0,
	},
	empty: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 14,
		paddingBlock: 64,
		textAlign: "center",
		color: color.textMuted,
	},
	dialog: { width: 520, overflowY: "auto" },
	form: {
		display: "flex",
		flexDirection: "column",
		gap: 18,
		padding: 32,
		fontSize: font.size_3,
	},
	formFields: {
		width: "100%",
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		gap: 12,
		marginTop: 16,
	},
	notes: {
		width: "100%",
		minHeight: 96,
		marginTop: 6,
		padding: 10,
		borderRadius: radius.md,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		backgroundColor: color.backgroundRaised,
		color: color.textMain,
		boxSizing: "border-box",
		fontSize: font.size_3,
		resize: "vertical",
	},
	badge: {
		fontSize: 11,
		paddingBlock: 3,
		paddingInline: 8,
		borderRadius: radius.md,
		backgroundColor: color.surfaceWhite02,
		color: color.textMuted,
		borderColor: color.border,
		borderStyle: "solid",
		borderWidth: 1,
	},
	main: {
		flex: 1,
		height: "100%",
		minHeight: 0,
		minWidth: 0,
		overflowY: "auto",
		paddingBlock: 32,
		paddingInline: "clamp(24px, 4vw, 72px)",
		color: color.textMain,
		fontSize: font.size_3,
		width: "100%",
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		gap: 16,
		alignItems: "flex-start",
	},
	row: { display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" },
	card: {
		width: "100%",
		boxSizing: "border-box",
		flexShrink: 0,
		backgroundColor: color.surfaceWhite02,
		borderColor: color.border,
		borderStyle: "solid",
		borderWidth: 1,
		borderRadius: radius.md,
		padding: 18,
		alignItems: "flex-start",
		display: "flex",
		flexDirection: "column",
		gap: 10,
	},
	input: {
		width: "100%",
		boxSizing: "border-box",
		backgroundColor: color.backgroundRaised,
		color: color.textMain,
		borderColor: color.border,
		borderStyle: "solid",
		borderWidth: 1,
		borderRadius: radius.md,
		padding: 8,
		marginTop: 6,
		minHeight: 34,
		fontSize: font.size_3,
	},
	code: {
		width: "100%",
		minHeight: 160,
		boxSizing: "border-box",
		backgroundColor: color.backgroundRaised,
		color: color.textMain,
		borderColor: color.border,
		borderStyle: "solid",
		borderWidth: 1,
		borderRadius: radius.md,
		padding: 10,
		fontFamily: "monospace",
		fontSize: 12,
		resize: "vertical",
	},
	muted: {
		color: color.textSoft,
		fontSize: font.size_3,
		overflowWrap: "anywhere",
	},
	pre: {
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
		fontSize: 12,
		maxHeight: 320,
		overflowY: "auto",
	},
	title: {
		marginBlock: 6,
		fontSize: 22,
		fontWeight: 500,
		letterSpacing: "-0.025em",
	},
});
