// Explicit imports keep unsupported grammars and themes out of the renderer build.
export const syntaxLanguages = {
	bash: () => import("@shikijs/langs/bash"),
	c: () => import("@shikijs/langs/c"),
	cpp: () => import("@shikijs/langs/cpp"),
	css: () => import("@shikijs/langs/css"),
	dart: () => import("@shikijs/langs/dart"),
	go: () => import("@shikijs/langs/go"),
	graphql: () => import("@shikijs/langs/graphql"),
	html: () => import("@shikijs/langs/html"),
	java: () => import("@shikijs/langs/java"),
	javascript: () => import("@shikijs/langs/javascript"),
	json: () => import("@shikijs/langs/json"),
	jsx: () => import("@shikijs/langs/jsx"),
	kotlin: () => import("@shikijs/langs/kotlin"),
	lua: () => import("@shikijs/langs/lua"),
	markdown: () => import("@shikijs/langs/markdown"),
	php: () => import("@shikijs/langs/php"),
	python: () => import("@shikijs/langs/python"),
	r: () => import("@shikijs/langs/r"),
	ruby: () => import("@shikijs/langs/ruby"),
	rust: () => import("@shikijs/langs/rust"),
	scala: () => import("@shikijs/langs/scala"),
	scss: () => import("@shikijs/langs/scss"),
	sql: () => import("@shikijs/langs/sql"),
	svelte: () => import("@shikijs/langs/svelte"),
	swift: () => import("@shikijs/langs/swift"),
	toml: () => import("@shikijs/langs/toml"),
	tsx: () => import("@shikijs/langs/tsx"),
	typescript: () => import("@shikijs/langs/typescript"),
	vue: () => import("@shikijs/langs/vue"),
	yaml: () => import("@shikijs/langs/yaml"),
	zig: () => import("@shikijs/langs/zig"),
};
export const syntaxThemes = {
	"github-dark-high-contrast": () =>
		import("@shikijs/themes/github-dark-high-contrast"),
	"vitesse-dark": () => import("@shikijs/themes/vitesse-dark"),
	"one-dark-pro": () => import("@shikijs/themes/one-dark-pro"),
	dracula: () => import("@shikijs/themes/dracula"),
	"slack-dark": () => import("@shikijs/themes/slack-dark"),
};
