import * as stylex from "@octanejs/stylex";
import type { CSSProperties } from "react";
import {
	color,
	controlSize,
	font,
	layer,
	motion,
	radius,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	iconDim: {
		opacity: 0.6,
	},
	noShrink: {
		flexShrink: 0,
	},
	paneSummaryCard: {
		position: "relative",
	},
	paneSummary: {
		alignItems: "flex-start",
		display: "flex",
		gap: controlSize._2,
		marginBottom: "0.125rem",
		paddingBlock: "0.375rem",
		paddingLeft: controlSize._2,
		paddingRight: controlSize._8,
		textAlign: "left",
		width: "100%",
	},
	paneSummaryIcon: {
		flexShrink: 0,
		marginTop: "0.125rem",
	},
	paneSummaryText: {
		flex: 1,
		minWidth: controlSize._0,
	},
	paneSummaryDelete: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		borderRadius: radius.sm,
		color: {
			default: color.textFaint,
			":hover": color.textMain,
		},
		display: "flex",
		height: controlSize._5,
		justifyContent: "center",
		position: "absolute",
		right: controlSize._1,
		top: "50%",
		transform: "translateY(-50%)",
		width: controlSize._5,
	},
	paneSummaryTitle: {
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		lineHeight: 1.2,
		margin: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	repositoryEmptyState: {
		color: color.textFaint,
		fontSize: font.size_2,
		paddingBlock: controlSize._6,
		paddingInline: controlSize._2,
		textAlign: "center",
	},
	sidebarModeTabs: {
		display: "grid",
		gridTemplateColumns: "1fr 1fr",
		gap: controlSize._1,
		marginTop: controlSize._1,
	},
	sidebarToolbar: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._1,
		paddingBottom: controlSize._2,
		paddingInline: controlSize._3,
	},
	sidebarRepositoryActions: {
		display: "flex",
	},
	sidebarRepositoryAction: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		borderRadius: radius.sm,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		display: "flex",
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		gap: controlSize._1,
		height: controlSize._7,
		justifyContent: "center",
		":disabled": {
			color: color.textMuted,
			cursor: "default",
			opacity: 0.45,
		},
	},
	sidebarModeTab: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._1,
		height: controlSize._7,
		justifyContent: "center",
		fontSize: font.size_2,
		fontWeight: font.weight_5,
	},
	workspacePaneList: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._2,
		marginTop: "0.125rem",
		paddingBottom: controlSize._1,
	},
	shell: {
		backdropFilter: "none",
		backgroundColor: color.background,
		borderRadius: radius.none,
		borderWidth: controlSize._0,
		borderRightWidth: 1,
		borderRightStyle: "solid",
		borderRightColor: color.border,
		boxSizing: "border-box",
		boxShadow: "none",
		display: "flex",
		flexDirection: "column",
		marginTop: controlSize._0,
		overflow: "visible",
		paddingTop: controlSize._0,
		position: "relative",
		transitionDuration: motion.durationSlow,
		transitionProperty: "width",
		transitionTimingFunction: "ease",
		userSelect: "none",
	},
	shellHidden: {
		backgroundColor: color.transparent,
		borderColor: color.transparent,
		boxShadow: "none",
		width: controlSize._0,
	},
	shellOpen: {
		width: 233,
	},
	shellResizing: {
		transitionDuration: motion.durationInstant,
		transitionProperty: "none",
		userSelect: "none",
	},
	resizeHandle: {
		position: "absolute",
		top: controlSize._0,
		right: -2,
		bottom: controlSize._0,
		zIndex: layer.sticky,
		width: controlSize._1,
		borderWidth: 0,
		cursor: "ew-resize",
		padding: controlSize._0,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlActive,
		},
		transitionProperty: "background-color",
		transitionDuration: motion.durationFast,
	},
	nav: {
		display: "flex",
		flex: 1,
		minHeight: controlSize._0,
		overflow: "hidden",
		paddingLeft: controlSize._0,
		paddingBottom: controlSize._12,
		paddingBlock: controlSize._0,
	},
	sidebarSettings: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._2,
		height: controlSize._9,
		width: "100%",
		paddingInline: controlSize._2,
		borderRadius: radius.md,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		color: color.textSoft,
		fontSize: font.size_2,
	},
	sidebarAccountArea: {
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		gap: controlSize._0_5,
		marginBlock: controlSize._2,
		paddingInline: controlSize._3,
		width: "100%",
	},
	sidebarAccount: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		borderRadius: radius.md,
		color: color.textSoft,
		display: "flex",
		fontSize: font.size_2,
		gap: controlSize._2,
		height: controlSize._9,
		minWidth: controlSize._0,
		paddingInline: controlSize._2,
		textAlign: "left",
		width: "100%",
	},
	sidebarAvatar: {
		borderColor: color.border,
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		height: controlSize._5,
		objectFit: "cover",
		width: controlSize._5,
	},
	sidebarAvatarFallback: {
		alignItems: "center",
		backgroundColor: color.controlActive,
		borderRadius: radius.pill,
		display: "flex",
		flexShrink: 0,
		height: controlSize._5,
		justifyContent: "center",
		width: controlSize._5,
	},
	sidebarUsername: {
		minWidth: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	workspaceSection: {
		display: "flex",
		flex: 1,
		minHeight: controlSize._0,
		flexDirection: "column",
		marginTop: controlSize._0,
		paddingTop: controlSize._2,
		minWidth: controlSize._0,
		width: "100%",
	},
	workspaceListScroll: {
		minHeight: controlSize._0,
		overflowY: "auto",
		paddingInline: controlSize._3,
	},
	workspaceSectionHeader: {
		position: "relative",
		zIndex: layer.modal,
		alignItems: "center",
		display: "none",
		marginBlockEnd: controlSize._1,
		marginInline: "0.375rem",
	},
	workspaceSectionHeaderCollapsed: {
		justifyContent: "flex-start",
	},
	workspaceSectionHeaderOpen: {
		justifyContent: "space-between",
		paddingInline: controlSize._1,
	},
	collapsedAddButton: {
		borderRadius: radius.circle,
		height: controlSize._8,
		width: controlSize._8,
	},
	workspaceLayoutControl: {
		position: "relative",
		isolation: "isolate",
		display: "inline-flex",
		height: controlSize._7,
		alignItems: "center",
		gap: controlSize._1,
		borderWidth: 0,
		borderRadius: radius.none,
		backgroundColor: color.transparent,
		overflow: "visible",
	},
	workspaceGridWrap: {
		position: "relative",
		zIndex: layer.content,
		display: "inline-flex",
		height: "100%",
		width: controlSize._7,
		flexShrink: 0,
	},
	workspaceGridMenuAnchor: {
		position: "absolute",
		top: 42,
		left: controlSize._0,
		zIndex: layer.sidebarPopover,
		display: "flex",
		width: 188,
		pointerEvents: "auto",
		transformOrigin: "top left",
		animationName: stylex.keyframes({
			from: {
				opacity: 0,
				transform: "translateY(-10px) scale(0.97)",
			},
			to: {
				opacity: 1,
				transform: "translateY(0) scale(1)",
			},
		}),
		animationDuration: motion.durationDeliberate,
		animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
	},
	workspaceLayoutButton: {
		position: "relative",
		zIndex: layer.content,
		display: "inline-flex",
		height: "100%",
		width: controlSize._7,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.transparent,
		borderRadius: radius.circle,
	},
	workspaceLayoutButtonIdle: {
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	workspaceLayoutButtonActive: {
		color: color.textMain,
		backgroundColor: color.transparent,
		borderColor: color.border,
		boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.08)",
	},
	workspaceGridMenu: {
		boxSizing: "border-box",
		display: "flex",
		width: 188,
		flexDirection: "column",
		gap: controlSize._2,
		borderWidth: 0,
		borderRadius: radius.lg,
		backgroundColor: color.transparent,
		boxShadow: "none",
		padding: controlSize._2,
	},
	workspaceGridMenuRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: controlSize._2,
	},
	workspaceGridMenuLabel: {
		color: color.textMuted,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
	},
	workspaceGridMenuHint: {
		color: color.textFaint,
		fontSize: font.size_1,
		lineHeight: 1.4,
		paddingInline: controlSize._1,
	},
	workspaceGridChoices: {
		position: "relative",
		isolation: "isolate",
		display: "flex",
		gap: controlSize._0_5,
	},
	workspaceGridChoice: {
		position: "relative",
		zIndex: layer.content,
		display: "inline-flex",
		height: controlSize._6,
		width: controlSize._6,
		alignItems: "center",
		justifyContent: "center",
		borderRadius: radius.circle,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		backgroundColor: {
			default: color.transparent,
			":hover": color.transparent,
		},
		fontSize: font.size_1,
	},
	workspaceGridChoiceActive: {
		color: color.textMain,
		backgroundColor: color.transparent,
	},
	flipHorizontal: {
		transform: "scaleX(-1)",
	},
	updateButton: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		borderRadius: radius.md,
		color: color.textSoft,
		display: "flex",
		fontSize: font.size_2,
		gap: controlSize._2,
		height: controlSize._9,
		paddingInline: controlSize._2,
		textAlign: "left",
		width: "100%",
	},
	updateButtonBusy: {
		cursor: "wait",
		opacity: 0.75,
	},
	updateLabel: {
		flex: 1,
		minWidth: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
});

export function getWorkspaceSidebarAsideStyle(
	width: CSSProperties["width"],
): CSSProperties {
	return { width: width } as CSSProperties;
}
