import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	effect,
	font,
	motion,
	radius,
	shadow,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	root: {
		boxSizing: "border-box",
		maxWidth: "100%",
		minWidth: controlSize._0,
		overflow: "hidden",
		position: "relative",
		width: "100%",
	},
	compactRoot: {
		boxSizing: "border-box",
		maxWidth: "100%",
		minWidth: controlSize._0,
		overflow: "hidden",
		width: "100%",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._3,
		backgroundColor: color.popoverOpaque,
		backgroundImage: effect.popoverDepth,
		boxShadow:
			"inset 0 1px 0 rgba(255, 255, 255, 0.05), 0 24px 54px rgba(0, 0, 0, 0.64)",
	},
	compactList: {
		maxHeight: "210px",
		overflowY: "auto",
		paddingBlock: controlSize._0,
	},
	resultRow: {
		display: "flex",
		width: "100%",
		alignItems: "center",
		gap: controlSize._2,
		color: color.textSoft,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._3,
		textAlign: "left",
		transitionProperty: "background-color, color",
		transitionDuration: motion.durationFast,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		backgroundImage: {
			default: "none",
			":hover": effect.controlDepth,
		},
	},
	resultRowActive: {
		backgroundColor: color.controlHover,
		backgroundImage: effect.controlDepth,
		color: color.textMain,
	},
	resultRowActiveAccent: {
		backgroundColor: color.controlActive,
		backgroundImage: effect.controlDepthHover,
		color: color.textMain,
	},
	resultIcon: {
		flexShrink: 0,
		color: color.textMuted,
	},
	accentText: {
		color: color.textSoft,
	},
	resultText: {
		minWidth: controlSize._0,
		flex: 1,
	},
	resultName: {
		display: "block",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: font.size_3,
		fontWeight: font.weight_5,
	},
	resultPath: {
		display: "block",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_2,
	},
	resultPathSmall: {
		display: "block",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_1,
	},
	chevron: {
		flexShrink: 0,
		color: color.textMuted,
	},
	selectedBar: {
		display: "flex",
		minWidth: controlSize._0,
		flexWrap: "wrap",
		gap: controlSize._1,
		overflow: "hidden",
		paddingBlock: controlSize._2,
		paddingInline: controlSize._3,
	},
	selectedTag: {
		display: "inline-flex",
		maxWidth: "140px",
		alignItems: "center",
		gap: controlSize._1,
		borderRadius: radius.md,
		backgroundColor: color.surfaceWhite05,
		backgroundImage: effect.controlDepth,
		color: color.textSoft,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
		paddingBlock: "0.125rem",
		paddingInline: "0.375rem",
	},
	selectedTagStrong: {
		display: "inline-flex",
		alignItems: "center",
		gap: controlSize._1,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.controlActive,
		backgroundImage: effect.controlDepth,
		color: color.textSoft,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
		paddingBlock: "0.125rem",
		paddingInline: "0.375rem",
	},
	truncate: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	tagRemove: {
		flexShrink: 0,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		transitionProperty: "color",
		transitionDuration: motion.durationFast,
	},
	moreCount: {
		color: color.textMuted,
		fontSize: font.size_1,
	},
	spinner: {
		width: font.size_3,
		height: font.size_3,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.textMuted,
		borderTopColor: color.transparent,
		borderRadius: radius.pill,
		animationName: stylex.keyframes({
			to: {
				transform: "rotate(360deg)",
			},
		}),
		animationDuration: motion.durationLonger,
		animationTimingFunction: "linear",
		animationIterationCount: "infinite",
	},
	selectedWrap: {
		borderBlockWidth: 0,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._2,
	},
	selectedList: {
		display: "flex",
		maxHeight: "60px",
		flexWrap: "wrap",
		gap: controlSize._1,
		overflowY: "auto",
	},
	unifiedFrame: {
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		maxWidth: "100%",
		minWidth: controlSize._0,
		width: "100%",
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._3,
		backgroundColor: color.backgroundSubtle,
		backgroundImage: "none",
		boxShadow: "none",
	},
	unifiedList: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: controlSize._0,
		maxHeight: "220px",
		overflowY: "auto",
		borderBlockWidth: 0,
		paddingBlock: controlSize._0_5,
	},
	resultRowCompact: {
		display: "flex",
		width: "100%",
		minWidth: controlSize._0,
		alignItems: "center",
		borderRadius: controlSize._2,
		gap: controlSize._2,
		color: color.textSoft,
		paddingBlock: controlSize._1,
		paddingInline: controlSize._2,
		textAlign: "left",
		transitionProperty: "background-color, color",
		transitionDuration: motion.durationFast,
		backgroundColor: color.transparent,
		backgroundImage: "none",
	},
	inputRow: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._2,
		minWidth: controlSize._0,
		borderBlockWidth: 0,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._2,
	},
	inputIcon: {
		flexShrink: 0,
		color: color.textMuted,
	},
	input: {
		minWidth: controlSize._0,
		flex: 1,
		backgroundColor: color.transparent,
		borderWidth: 0,
		color: color.textMain,
		fontSize: font.size_4,
		outline: "none",
		"::placeholder": {
			color: color.textMuted,
		},
	},
	startButton: {
		flexShrink: 0,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.md,
		backgroundColor: color.controlActive,
		backgroundImage: effect.controlDepth,
		boxShadow: shadow.controlDepth,
		color: color.textSoft,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		paddingBlock: "0.125rem",
		paddingInline: controlSize._2,
		transitionProperty: "background-color, color",
		transitionDuration: motion.durationFast,
		":hover": {
			backgroundColor: color.controlHover,
		},
	},
});
