import * as stylex from "@octanejs/stylex";
import type { CSSProperties } from "react";
import {
	color,
	controlSize,
	font,
	layer,
	motion,
	radius,
	shadow,
} from "../../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	root: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		minWidth: controlSize._0,
		backgroundColor: color.transparent,
	},
	collapsedRoot: {
		display: "flex",
		width: 37,
		height: "100%",
		alignItems: "center",
		flexDirection: "column",
		backgroundColor: color.transparent,
	},
	collapsedToggle: {
		display: "flex",
		width: "100%",
		height: controlSize._8,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	collapsedCounts: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: controlSize._3,
		paddingTop: controlSize._3,
	},
	collapsedGraphButton: {
		display: "flex",
		width: controlSize._6,
		height: controlSize._6,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		marginTop: controlSize._2,
		borderRadius: radius.md,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	collapsedCount: {
		display: "flex",
		minWidth: controlSize._6,
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._1,
		color: color.textSoft,
		fontFamily: font.familyDiff,
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
	},
	unstagedDot: {
		width: controlSize._1_25,
		height: controlSize._1_25,
		borderRadius: radius.pill,
		backgroundColor: color.warning,
	},
	stagedDot: {
		width: controlSize._1_25,
		height: controlSize._1_25,
		borderRadius: radius.pill,
		backgroundColor: color.gitAdded,
	},
	scrollArea: {
		flex: 1,
		minHeight: controlSize._0,
		overflowY: "auto",
	},
	splitArea: {
		display: "flex",
		flex: 1,
		minHeight: controlSize._0,
		flexDirection: "column",
		overflow: "hidden",
	},
	emptyState: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		paddingBlock: controlSize._6,
	},
	loadingState: {
		alignItems: "center",
		color: color.textMuted,
		display: "flex",
		fontSize: font.size_2,
		gap: controlSize._2,
	},
	emptyStateLarge: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		paddingBlock: controlSize._8,
	},
	emptyText: {
		color: color.surfaceWhite25,
		fontSize: font.size_2,
	},
	centerText: {
		paddingInline: controlSize._3,
		textAlign: "center",
	},
	mutedText: {
		color: color.textMuted,
		fontSize: font.size_2,
	},
	mutedTextSmall: {
		color: color.textMuted,
		fontSize: font.size_1,
	},
	sidebarHeader: {
		position: "sticky",
		top: controlSize._0,
		zIndex: layer.dropdown,
		display: "flex",
		height: controlSize._8,
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._2,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		backgroundColor: color.background,
		paddingInline: controlSize._3,
		paddingBlock: controlSize._0,
	},
	changeTotals: {
		display: "flex",
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._1_5,
		fontFamily: font.familyDiff,
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
	},
	spacer: {
		flex: 1,
	},
	segmented: {
		display: "flex",
		height: controlSize._5,
		alignItems: "center",
		gap: controlSize._0_5,
		backgroundColor: color.transparent,
	},
	segmentButton: {
		display: "flex",
		height: "100%",
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._1,
		paddingInline: controlSize._2,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
	},
	headerIconButton: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		borderColor: color.transparent,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 1,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		display: "inline-flex",
		height: controlSize._5,
		justifyContent: "center",
		width: controlSize._5,
		transitionProperty: "background-color, border-color, color",
		transitionDuration: motion.durationFast,
	},
	headerIconButtonActive: {
		backgroundColor: color.controlActive,
		borderColor: color.borderStrong,
		color: color.textMain,
	},
	commitSection: {
		display: "flex",
		flexShrink: 0,
		flexDirection: "column",
		backgroundColor: color.transparent,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: color.border,
		boxShadow: "0 -10px 24px rgba(0, 0, 0, 0.16)",
	},
	sectionTitle: {
		color: color.textMain,
		fontSize: font.size_2_75,
		fontWeight: font.weight_5,
	},
	fileGroupTitle: {
		color: color.textSoft,
		fontSize: font.size_2,
	},
	commitForm: {
		display: "flex",
		order: 2,
		flexDirection: "column",
		gap: controlSize._1_5,
		paddingInline: controlSize._2,
		paddingBlock: controlSize._2,
	},
	commitEditor: {
		height: controlSize._7,
		backgroundColor: color.backgroundRaised,
		borderColor: {
			default: color.border,
			":focus-within": color.borderStrong,
		},
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 1,
		boxShadow: {
			default: shadow.composerFrame,
			":focus-within": shadow.composerFrameFocus,
		},
		overflow: "hidden",
		transitionDuration: motion.durationBase,
		transitionProperty: "border-color, box-shadow, background-color",
	},
	commitEditorLiquid: {
		backgroundColor: color.transparent,
		borderColor: color.transparent,
		borderRadius: radius.md,
		boxShadow: "none",
	},
	summaryRow: {
		display: "flex",
		height: "100%",
		alignItems: "center",
	},
	summaryInput: {
		minWidth: controlSize._0,
		height: "100%",
		flex: 1,
		backgroundColor: color.transparent,
		color: color.textMain,
		fontSize: font.size_3,
		fontWeight: font.weight_5,
		outline: "none",
		paddingBlock: controlSize._0,
		paddingInline: controlSize._3,
		"::placeholder": {
			color: color.textFaint,
		},
	},
	generateMessageButton: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite06,
		},
		borderRadius: radius.md,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		display: "flex",
		flexShrink: 0,
		height: controlSize._6,
		justifyContent: "center",
		marginRight: controlSize._2,
		width: controlSize._6,
		":disabled": {
			opacity: 0.45,
		},
	},
	commitButtonSurface: {
		display: "flex",
		width: "100%",
		height: controlSize._7,
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.textWarmWhite,
		borderRadius: radius.md,
		backgroundColor: color.textWarmWhite,
		boxShadow: "inset 0 0 0 1px rgba(0, 0, 0, 0.12)",
	},
	commitMainAction: {
		display: "flex",
		minWidth: controlSize._0,
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._1_5,
		backgroundColor: {
			default: color.transparent,
			":hover": "rgba(0, 0, 0, 0.06)",
		},
		color: color.textWarmInk,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		":disabled": {
			color: color.textWarmInk,
			opacity: 1,
			WebkitTextFillColor: "#111210",
		},
	},
	detailsRoot: {
		display: "flex",
		height: "100%",
		flexDirection: "column",
	},
	detailsHeader: {
		flexShrink: 0,
		display: "flex",
		flexDirection: "column",
		gap: controlSize._2,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		padding: controlSize._3,
	},
	detailIdentityGrid: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr)",
		gap: controlSize._3,
	},
	detailIdentity: {
		display: "flex",
		minWidth: controlSize._0,
		alignItems: "center",
		gap: controlSize._2,
	},
	detailIdentityCopy: {
		display: "flex",
		minWidth: controlSize._0,
		flexDirection: "column",
	},
	detailAvatar: {
		display: "flex",
		width: controlSize._8,
		height: controlSize._8,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderStrong,
		borderRadius: radius.pill,
		backgroundColor: color.surfaceControl,
		color: color.textSoft,
		fontSize: font.size_1,
		fontWeight: font.weight_6,
	},
	detailAvatarImage: {
		display: "block",
		width: "100%",
		height: "100%",
		objectFit: "cover",
	},
	comparisonRange: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._2,
		color: color.textMain,
		fontFamily: font.familyMono,
		fontSize: font.size_2_75,
	},
	detailIdentityLabel: {
		display: "block",
		marginBottom: controlSize._1,
		color: color.textMuted,
		fontSize: font.size_1,
		fontWeight: font.weight_6,
		letterSpacing: "0.08em",
		textTransform: "uppercase",
	},
	commitMessage: {
		color: color.textMain,
		display: "-webkit-box",
		fontSize: font.size_4,
		fontWeight: font.weight_5,
		lineHeight: 1.4,
		overflow: "hidden",
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: 2,
	},
	commitDescriptionViewport: {
		flexShrink: 1,
		lineHeight: 1.4,
		minHeight: controlSize._0,
		maxHeight: "8.4em",
		outline: "none",
		overflow: "auto",
	},
	commitDescription: {
		color: color.textMain,
		cursor: "text",
		fontSize: font.size_2,
		whiteSpace: "pre-wrap",
	},
	authorText: {
		color: color.textSoft,
		fontSize: font.size_2,
	},
	fileStats: {
		flexShrink: 0,
		display: "flex",
		alignItems: "center",
		gap: controlSize._1,
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
	},
	addedText: {
		color: color.diffAdded,
	},
	deletedText: {
		color: color.diffRemoved,
	},
	statusIcon: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		fontSize: font.size_0,
		fontWeight: font.weightBold,
		lineHeight: 1,
		filter: "drop-shadow(0 1px 1px rgba(0, 0, 0, 0.95))",
	},
	fileChangeIcon: {
		position: "relative",
		display: "inline-flex",
		width: 17,
		height: 17,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
	},
	fileChangeMark: {
		position: "absolute",
		right: -2,
		top: -2,
		width: controlSize._2,
		height: controlSize._2,
		pointerEvents: "none",
	},
	modified: {
		color: color.diffModified,
	},
	addedStatus: {
		color: color.diffAdded,
	},
	deletedStatus: {
		color: color.diffRemoved,
	},
	renamedStatus: {
		color: color.diffRenamed,
	},
	defaultStatus: {
		color: color.textSoft,
	},
	fileGroup: {
		display: "flex",
		flexShrink: 0,
		flexDirection: "column",
	},
	splitFileGroup: {
		boxSizing: "border-box",
		flexGrow: 0,
		flexShrink: 0,
		height: "50%",
		minHeight: "50%",
		maxHeight: "50%",
		overflow: "hidden",
	},
	emptyGroupBody: {
		height: controlSize._12,
		flexShrink: 0,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	emptyGroupText: {
		color: color.textFaint,
		fontSize: font.size_2,
	},
	groupHeader: {
		display: "flex",
		height: controlSize._8,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		backgroundColor: color.transparent,
		paddingInline: controlSize._3,
		gap: controlSize._2,
	},
	groupHeaderSeparated: {
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: color.border,
	},
	groupToggle: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._2,
		backgroundColor: color.transparent,
	},
	cursorPointer: {
		cursor: "pointer",
	},
	cursorDefault: {
		cursor: "default",
	},
	chevron: {
		flexShrink: 0,
		color: color.textMuted,
		transitionProperty: "transform",
		transitionDuration: motion.durationFast,
	},
	chevronOpen: {
		transform: "rotate(90deg)",
	},
	countPill: {
		display: "flex",
		minWidth: controlSize._5,
		height: controlSize._4,
		alignItems: "center",
		justifyContent: "center",
		borderRadius: radius.pill,
		backgroundColor: color.surfaceControl,
		color: color.textMain,
		fontSize: font.size_1,
		fontWeight: font.weight_6,
		fontVariantNumeric: "tabular-nums",
		paddingInline: controlSize._1_5,
	},
	actionAllButton: {
		height: controlSize._5,
		flexShrink: 0,
		whiteSpace: "nowrap",
	},
	groupList: {
		flexShrink: 0,
		backgroundColor: color.transparent,
	},
	splitGroupList: {
		flexGrow: 1,
		flexShrink: 1,
		minHeight: controlSize._0,
		overflowY: "auto",
		overscrollBehavior: "contain",
	},
	pathRow: {
		position: "relative",
		display: "flex",
		contentVisibility: "auto",
		containIntrinsicSize: `auto ${controlSize._6}`,
		alignItems: "center",
		gap: controlSize._2,
		borderLeftWidth: 2,
		borderLeftStyle: "solid",
		borderLeftColor: color.transparent,
		paddingBlock: controlSize._1,
		paddingInline: controlSize._3,
		transitionProperty: "background-color, border-color",
		transitionDuration: motion.durationFast,
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceSubtle,
		},
	},
	treeRow: {
		position: "relative",
		display: "flex",
		contentVisibility: "auto",
		containIntrinsicSize: `auto ${controlSize._5}`,
		height: controlSize._5,
		cursor: "pointer",
		alignItems: "center",
		gap: controlSize._1,
		borderLeftWidth: 2,
		borderLeftStyle: "solid",
		borderLeftColor: color.transparent,
		transitionProperty: "background-color, border-color",
		transitionDuration: motion.durationFast,
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceSubtle,
		},
	},
	treeNodeButton: {
		alignItems: "center",
		backgroundColor: color.transparent,
		cursor: "pointer",
		display: "flex",
		flex: 1,
		gap: controlSize._1,
		height: "100%",
		minWidth: controlSize._0,
		padding: controlSize._0,
		textAlign: "left",
	},
	fileRowActive: {
		borderLeftColor: color.borderStrong,
		backgroundColor: color.surfaceInset,
	},
	fileButton: {
		minWidth: controlSize._0,
		flex: 1,
		display: "flex",
		justifyContent: "flex-end",
		textAlign: "left",
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		lineHeight: 1.3,
	},
	pathDirectory: {
		flex: "0 1 auto",
		minWidth: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
	},
	fileRowButton: {
		display: "flex",
		minWidth: controlSize._0,
		flex: 1,
		alignItems: "center",
		gap: controlSize._2,
		backgroundColor: color.transparent,
		textAlign: "left",
	},
	pathFileName: {
		flexShrink: 0,
		maxWidth: "100%",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		lineHeight: 1.3,
		transitionProperty: "color",
		transitionDuration: motion.durationFast,
	},
	activeText: {
		color: color.textMain,
	},
	rowAction: {
		position: "absolute",
		right: controlSize._2,
		top: "50%",
		zIndex: layer.control,
		transform: "translateY(-50%)",
		display: "flex",
		width: "1.125rem",
		height: "1.125rem",
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.circle,
		backgroundColor: {
			default: color.backgroundRaised,
			":hover": color.controlHover,
		},
		color: color.textSoft,
		opacity: 0,
		pointerEvents: "none",
		transitionProperty: "opacity, color, background-color, border-color",
		transitionDuration: motion.durationFast,
	},
	rowActionVisible: {
		opacity: 1,
		pointerEvents: "auto",
		color: {
			default: color.textSoft,
			":hover": color.textMain,
		},
	},
	rowActionSubtle: {
		position: "absolute",
		right: controlSize._2,
		top: "50%",
		zIndex: layer.control,
		transform: "translateY(-50%)",
		display: "flex",
		width: "1.125rem",
		height: "1.125rem",
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.circle,
		backgroundColor: {
			default: color.backgroundRaised,
			":hover": color.controlHover,
		},
		color: color.textSoft,
		opacity: 0,
		pointerEvents: "none",
		transitionProperty: "opacity, color, background-color, border-color",
		transitionDuration: motion.durationFast,
	},
	folderIcon: {
		flexShrink: 0,
		color: color.textMuted,
		transitionProperty: "color",
		transitionDuration: motion.durationFast,
	},
	folderIconOpen: {
		color: color.textSoft,
	},
	treeName: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textSoft,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
	},
	treeIndentSpacer: {
		width: controlSize._2,
		flexShrink: 0,
	},
	treeFileName: {
		minWidth: controlSize._0,
		flex: 1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		transitionProperty: "color",
		transitionDuration: motion.durationFast,
	},
});

export function getCommitDetailsPanelCommitDescriptionViewportStyle(): CSSProperties {
	return { maxHeight: "8.4em", overflow: "auto" } as CSSProperties;
}

export function getTreeNodeRowTreeRowStyle(
	paddingLeft: CSSProperties["paddingLeft"],
): CSSProperties {
	return { paddingLeft: paddingLeft, paddingRight: 6 } as CSSProperties;
}
