import * as stylex from "@stylexjs/stylex";
import { color } from "../../../design-system/styles.stylex.ts";
export const cardStyles = stylex.create({
	card: {
		width: "100%",
		boxSizing: "border-box",
		borderRadius: 12,
		overflow: "hidden",
		fontSize: 13,
		lineHeight: 1.5,
		color: color.textMain,
	},
	header: {
		display: "flex",
		alignItems: "center",
		gap: 10,
		padding: 12,
		paddingBottom: 10,
	},
	heading: { flex: 1, minWidth: 0 },
	title: { fontSize: 14, fontWeight: 600, overflowWrap: "anywhere" },
	status: { fontSize: 11, color: color.textMuted, margin: 0 },
	metadata: {
		display: "flex",
		flexWrap: "wrap",
		gap: 10,
		paddingInline: 12,
		paddingBottom: 10,
		fontSize: 12,
		color: color.textMuted,
	},
	item: {
		display: "inline-flex",
		alignItems: "center",
		gap: 6,
		minWidth: 0,
		maxWidth: "100%",
	},
	scope: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		maxWidth: 240,
	},
	instructions: {
		marginInline: 12,
		padding: 12,
		borderRadius: 8,
		border: 0,
		backgroundColor: color.transparent,
	},
	preview: {
		margin: 0,
		fontSize: 12,
		lineHeight: 1.65,
		color: color.textSoft,
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
		overflow: "hidden",
		display: "-webkit-box",
		WebkitLineClamp: 2,
		WebkitBoxOrient: "vertical",
	},
	expanded: {
		display: "block",
		maxHeight: 220,
		overflowY: "auto",
		overscrollBehavior: "contain",
		WebkitLineClamp: "unset",
	},
	footer: {
		display: "flex",
		flexWrap: "wrap",
		gap: 6,
		padding: 12,
		paddingInline: 12,
		alignItems: "center",
	},
	feedback: { margin: 0, paddingInline: 12, paddingTop: 10, fontSize: 12 },
});
