import * as stylex from "@stylexjs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	radius,
} from "../../../../design-system/styles.stylex.ts";
export const styles = stylex.create({
	root: {
		display: "flex",
		flex: 1,
		minHeight: 0,
		flexDirection: "column",
		overflow: "hidden",
	},
	toolbar: {
		alignItems: "center",
		borderBottomColor: color.border,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "flex",
		flexShrink: 0,
		gap: controlSize._3,
		justifyContent: "space-between",
		minHeight: controlSize._12,
		paddingInline: controlSize._6,
		paddingRight: controlSize._12,
	},
	commandGroup: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._2_5,
		minWidth: 0,
	},
	command: {
		alignItems: "center",
		color: color.textSoft,
		display: "flex",
		fontFamily: font.familyMono,
		fontSize: font.size_2,
		minWidth: 0,
		overflowWrap: "anywhere",
	},
	commandInput: {
		color: color.textSoft,
		fontFamily: font.familyMono,
		fontSize: font.size_2,
		marginInline: controlSize._0,
		minWidth: 0,
		paddingInline: controlSize._1,
		width: "min(13rem, 24vw)",
	},
	badge: {
		color: color.textMuted,
		flexShrink: 0,
		fontSize: font.size_1,
	},
	body: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._5,
		minHeight: 0,
		overflowY: "auto",
		paddingBlock: controlSize._6,
		paddingInline: {
			default: controlSize._6,
			"@media (max-width: 700px)": controlSize._4,
		},
	},
	identity: {
		display: "flex",
		flexDirection: "column",
		flexShrink: 0,
		gap: controlSize._2,
	},
	field: {
		backgroundColor: color.transparent,
		borderColor: color.transparent,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 1,
		boxSizing: "border-box",
		display: "block",
		marginInline: "-0.5rem",
		outline: "none",
		overflowWrap: "anywhere",
		paddingBlock: controlSize._1,
		paddingInline: controlSize._2,
		transitionDuration: motion.durationFast,
		transitionProperty: "background-color, border-color",
		width: "calc(100% + 1rem)",
	},
	fieldEditable: {
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite02,
			":focus": color.surfaceWhite04,
		},
		borderColor: {
			default: color.transparent,
			":focus": color.border,
		},
		"::placeholder": {
			color: color.textMuted,
		},
	},
	title: {
		color: color.textMain,
		fontSize: font.size_5,
		fontWeight: font.weight_6,
		letterSpacing: "-0.012em",
		lineHeight: 1.4,
		margin: 0,
	},
	description: {
		color: color.textMuted,
		fontSize: font.size_2,
		lineHeight: 1.6,
		margin: 0,
		minHeight: "1.6em",
		resize: "none",
	},
	document: {
		display: "flex",
		flexDirection: "column",
	},
	documentHeader: {
		alignItems: "center",
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "flex",
		justifyContent: "space-between",
		paddingBlock: controlSize._2,
	},
	documentTitle: {
		alignItems: "center",
		color: color.textSoft,
		display: "flex",
		fontSize: font.size_3,
		fontWeight: font.weight_5,
		gap: controlSize._2,
	},
	meta: {
		color: color.textMuted,
		fontSize: font.size_1,
		fontWeight: font.weightRegular,
	},
	instructions: {
		color: color.textSoft,
		fontFamily: font.familyMono,
		fontSize: font.size_2,
		lineHeight: 1.8,
		margin: 0,
		marginBlockStart: controlSize._2,
		minHeight: "13rem",
		resize: "none",
		whiteSpace: "pre-wrap",
	},
	footer: {
		alignItems: "center",
		borderTopColor: color.border,
		borderTopStyle: "solid",
		borderTopWidth: 1,
		display: "flex",
		flexShrink: 0,
		flexWrap: "wrap",
		gap: controlSize._2,
		justifyContent: "space-between",
		minHeight: controlSize._12,
		paddingBlock: controlSize._3,
		paddingInline: controlSize._6,
	},
	actions: {
		display: "flex",
		gap: controlSize._2,
	},
	deleteButton: {
		color: {
			default: color.textMuted,
			":hover": color.danger,
		},
	},
	error: {
		color: color.danger,
		fontSize: font.size_2,
		margin: 0,
	},
});
