import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	layer,
	radius,
	shadow,
} from "../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	trigger: {
		display: "flex",
		height: controlSize._8,
		alignItems: "center",
		gap: controlSize._2,
		paddingInline: controlSize._2,
		borderWidth: controlSize._0,
		borderRadius: radius.md,
		backgroundColor: {
			default: color.surfaceWhite06,
			":hover": color.surfaceWhite10,
		},
		color: color.textMain,
	},
	triggerLabel: { fontSize: font.size_2, fontWeight: font.weight_5 },
	shortcut: {
		color: color.textMuted,
		fontFamily: "inherit",
		fontSize: font.size_1,
	},
	backdrop: {
		position: "fixed",
		inset: controlSize._0,
		zIndex: layer.modal,
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "center",
		paddingTop: "15vh",
		backgroundColor: "rgba(0,0,0,0.36)",
		backdropFilter: "blur(3px)",
		pointerEvents: "auto",
	},
	palette: {
		width: "min(31rem, calc(100vw - 32px))",
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderStrong,
		borderRadius: radius.lg,
		backgroundColor: color.headerPopoverOpaque,
		boxShadow: shadow.popover,
	},
	search: {
		display: "flex",
		height: 48,
		alignItems: "center",
		gap: controlSize._2,
		paddingInline: controlSize._3,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		color: color.textSoft,
	},
	input: {
		flex: 1,
		minWidth: controlSize._0,
		borderWidth: controlSize._0,
		outline: "none",
		backgroundColor: color.transparent,
		color: color.textMain,
		fontSize: font.size_3,
	},
	escape: {
		paddingBlock: controlSize._1,
		paddingInline: controlSize._1_5,
		borderRadius: radius.sm,
		backgroundColor: color.surfaceWhite06,
		color: color.textMuted,
		fontFamily: "inherit",
		fontSize: font.size_1,
	},
	results: {
		display: "flex",
		maxHeight: "22rem",
		flexDirection: "column",
		overflowY: "auto",
		padding: controlSize._1_5,
	},
	command: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._3,
		width: "100%",
		paddingBlock: controlSize._2,
		paddingInline: controlSize._2,
		borderWidth: controlSize._0,
		borderRadius: radius.md,
		backgroundColor: color.transparent,
		color: color.textSoft,
		textAlign: "left",
	},
	commandActive: {
		backgroundColor: color.surfaceWhite08,
		color: color.textMain,
	},
	commandIcon: {
		display: "flex",
		width: controlSize._7,
		height: controlSize._7,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		borderRadius: radius.md,
		backgroundColor: color.surfaceWhite06,
	},
	commandCopy: {
		display: "flex",
		minWidth: controlSize._0,
		flexDirection: "column",
		gap: 2,
	},
	commandLabel: {
		color: "inherit",
		fontSize: font.size_2_75,
		fontWeight: font.weight_5,
	},
	commandDetail: { color: color.textMuted, fontSize: font.size_1 },
	empty: {
		padding: controlSize._6,
		color: color.textMuted,
		fontSize: font.size_2,
		textAlign: "center",
	},
});
