import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	radius,
	shadow,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	dialog: {
		position: "relative",
		margin: "auto",
		boxSizing: "border-box",
		backgroundColor: color.backgroundModal,
		color: color.textMain,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderStrong,
		borderRadius: radius._2xl,
		boxShadow: shadow.modal,
		width: "min(1080px, calc(100vw - 32px))",
		height: "min(780px, calc(100dvh - 48px))",
		maxWidth: "calc(100vw - 32px)",
		maxHeight: "calc(100dvh - 48px)",
		padding: 0,
		overflow: "hidden",
		"::backdrop": {
			backgroundColor: color.backgroundOverlay,
			backdropFilter: "blur(8px)",
		},
	},
	root: { display: "flex", height: "100%", flexDirection: "column" },
	brand: { display: "flex", alignItems: "center", gap: controlSize._3 },
	title: {
		margin: 0,
		fontSize: font.size_4,
		fontWeight: font.weight_6,
		letterSpacing: "-0.025em",
	},
	headerActions: { display: "flex", alignItems: "center", gap: controlSize._3 },
	closeButton: {
		position: "absolute",
		top: controlSize._3,
		right: controlSize._3,
		zIndex: 1,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: controlSize._8,
		height: controlSize._8,
		borderWidth: 0,
		borderRadius: radius.md,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		color: color.textMuted,
	},
	newButton: {
		display: "inline-flex",
		minHeight: controlSize._8,
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._1_5,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderControl,
		borderRadius: radius.lg,
		backgroundColor: {
			default: color.backgroundPanel,
			":hover": color.controlHover,
		},
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		paddingInline: controlSize._3,
		whiteSpace: "nowrap",
		":disabled": { opacity: 0.5 },
	},
	content: {
		display: "flex",
		flexDirection: { default: "row", "@media (max-width: 700px)": "column" },
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	listPane: {
		display: "flex",
		flexDirection: "column",
		width: { default: "270px", "@media (max-width: 700px)": "100%" },
		maxHeight: { default: "none", "@media (max-width: 700px)": "180px" },
		flexShrink: 0,
		minHeight: 0,
		borderRightWidth: 1,
		borderRightStyle: "solid",
		borderRightColor: color.border,
		backgroundColor: color.surfaceBlack14,
	},
	libraryNew: { width: "100%", marginBottom: controlSize._3 },
	libraryControls: {
		padding: controlSize._3,
		paddingRight: {
			default: controlSize._3,
			"@media (max-width: 700px)": controlSize._12,
		},
		paddingBottom: controlSize._1,
		flexShrink: 0,
	},
	searchWrap: { position: "relative" },
	searchIcon: {
		position: "absolute",
		left: controlSize._2_5,
		top: "50%",
		transform: "translateY(-50%)",
		color: color.textMuted,
		pointerEvents: "none",
	},
	searchInput: {
		width: "100%",
		height: controlSize._9,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.lg,
		backgroundColor: color.surfaceWhite02,
		color: color.textMain,
		fontSize: font.size_2,
		outline: "none",
		paddingLeft: controlSize._8,
		paddingRight: controlSize._2,
		":focus-visible": { borderColor: color.textMuted },
		"::placeholder": { color: color.textMuted },
	},
	libraryHeading: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		paddingBlock: controlSize._3,
		paddingInline: controlSize._1,
	},
	filter: {
		maxWidth: "85%",
		borderWidth: 0,
		backgroundColor: color.backgroundModal,
		color: color.textSoft,
		fontSize: font.size_1,
		cursor: "pointer",
	},
	count: {
		color: color.textMuted,
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
	},
	skillList: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._1,
		paddingInline: controlSize._2,
		paddingBottom: controlSize._3,
		overflowY: "auto",
		flex: 1,
		minHeight: 0,
	},
	skillRow: {
		display: "flex",
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._2_5,
		textAlign: "left",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.transparent,
		borderRadius: radius.lg,
		padding: controlSize._2_5,
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite04,
		},
		transitionProperty: "background-color, border-color",
		transitionDuration: motion.durationFast,
		":focus-visible": {
			outline: `1px solid ${color.textSoft}`,
			outlineOffset: "-2px",
		},
	},
	skillRowActive: {
		borderColor: color.borderControl,
		backgroundColor: {
			default: color.backgroundPanel,
			":hover": color.backgroundPanel,
		},
	},
	skillCopy: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._1,
		minWidth: 0,
		flex: 1,
	},
	skillCommand: {
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	skillDescription: {
		color: color.textSoft,
		fontSize: font.size_1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	builtinLabel: {
		color: color.textMuted,
		fontSize: font.size_0_5,
		flexShrink: 0,
	},
	footerTitle: {
		display: "block",
		marginBottom: controlSize._1,
		color: color.textSoft,
		fontWeight: font.weight_5,
	},
	emptyList: {
		padding: controlSize._4,
		color: color.textSoft,
		fontSize: font.size_2,
		lineHeight: 1.8,
	},
	detailPane: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minWidth: 0,
		minHeight: 0,
		overflow: "hidden",
	},
	builtInNotice: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		flexWrap: "wrap",
		gap: controlSize._2,
		flexShrink: 0,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._6,
		paddingRight: controlSize._12,
		color: color.textSoft,
		fontSize: font.size_1,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
	},
	copyButton: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._1_5,
		color: color.textMain,
		backgroundColor: color.transparent,
		borderWidth: 0,
		borderRadius: radius.md,
		padding: controlSize._1,
		":hover": { backgroundColor: color.surfaceControl },
	},
	editorEmpty: {
		display: "flex",
		flex: 1,
		minWidth: 0,
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._4,
		padding: controlSize._6,
		textAlign: "center",
	},
	emptyTitle: {
		color: color.textMain,
		fontSize: font.size_4,
		fontWeight: font.weight_5,
		letterSpacing: "-0.035em",
		margin: 0,
	},
	error: {
		color: color.danger,
		fontSize: font.size_2,
		paddingInline: controlSize._4,
	},
});
