import * as stylex from "@stylexjs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	radius,
	shadow,
} from "../../../../design-system/styles.stylex.ts";
export const styles = stylex.create({
	dialog: {
		position: "relative",
		margin: "auto",
		boxSizing: "border-box",
		backgroundColor: color.backgroundModal,
		color: color.textMain,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderStrong,
		borderRadius: radius._2xl,
		boxShadow: shadow.modal,
		width: "min(1080px, calc(100vw - 32px))",
		height: "min(780px, calc(100dvh - 48px))",
		maxWidth: "calc(100vw - 32px)",
		maxHeight: "calc(100dvh - 48px)",
		padding: 0,
		overflow: "hidden",
		"::backdrop": {
			backgroundColor: "rgba(0, 0, 0, 0.4)",
			backdropFilter: "blur(7px)",
		},
	},
	root: {
		display: "flex",
		height: "100%",
		flexDirection: "column",
	},
	closeButton: {
		position: "absolute",
		top: controlSize._3,
		right: controlSize._3,
		zIndex: 1,
	},
	content: {
		display: "flex",
		flexDirection: {
			default: "row",
			"@media (max-width: 700px)": "column",
		},
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	listPane: {
		backgroundColor: color.surfaceWhite02,
		borderRightColor: color.border,
		borderRightStyle: "solid",
		borderRightWidth: 1,
		display: "flex",
		flexDirection: "column",
		flexShrink: 0,
		maxHeight: {
			default: "none",
			"@media (max-width: 700px)": "200px",
		},
		minHeight: 0,
		width: {
			default: "17rem",
			"@media (max-width: 700px)": "100%",
		},
	},
	libraryControls: {
		display: "flex",
		flexDirection: "column",
		flexShrink: 0,
		gap: controlSize._2,
		paddingBlock: controlSize._4,
		paddingInline: controlSize._3,
		paddingRight: {
			default: controlSize._3,
			"@media (max-width: 700px)": controlSize._12,
		},
	},
	newButton: {
		justifyContent: "center",
		width: "100%",
	},
	searchWrap: {
		position: "relative",
	},
	searchIcon: {
		position: "absolute",
		left: controlSize._2_5,
		top: "50%",
		transform: "translateY(-50%)",
		color: color.textMuted,
		pointerEvents: "none",
	},
	searchInput: {
		backgroundColor: color.background,
		borderColor: {
			default: color.border,
			":focus": color.focusRing,
		},
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textMain,
		fontSize: font.size_2,
		height: controlSize._8,
		outline: "none",
		paddingLeft: controlSize._7,
		paddingRight: controlSize._2,
		width: "100%",
		"::placeholder": {
			color: color.textMuted,
		},
	},
	libraryHeading: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		justifyContent: "space-between",
		paddingBlock: controlSize._1,
		paddingInline: controlSize._4,
	},
	libraryHeadingLabel: {
		color: color.textMuted,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
		letterSpacing: "0.02em",
	},
	count: {
		color: color.textMuted,
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
	},
	skillList: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		minHeight: 0,
		overflowY: "auto",
		paddingBottom: controlSize._3,
		paddingInline: controlSize._2,
	},
	skillRow: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite06,
		},
		borderRadius: radius.lg,
		borderWidth: 0,
		display: "flex",
		flexShrink: 0,
		gap: controlSize._2_5,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._2_5,
		textAlign: "left",
		transitionDuration: motion.durationFast,
		transitionProperty: "background-color, color",
		":focus-visible": {
			outline: `1px solid ${color.textSoft}`,
			outlineOffset: "-2px",
		},
	},
	skillRowActive: {
		backgroundColor: {
			default: color.surfaceWhite08,
			":hover": color.surfaceWhite08,
		},
	},
	skillCopy: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: 0,
	},
	skillCommand: {
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	skillDescription: {
		color: color.textMuted,
		fontSize: font.size_1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	builtinLabel: {
		color: color.textMuted,
		flexShrink: 0,
		fontSize: font.size_0_5,
	},
	emptyList: {
		color: color.textMuted,
		display: "flex",
		flexDirection: "column",
		fontSize: font.size_2,
		gap: controlSize._1,
		lineHeight: 1.6,
		paddingBlock: controlSize._4,
		paddingInline: controlSize._2_5,
	},
	detailPane: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minWidth: 0,
		minHeight: 0,
		overflow: "hidden",
	},
	builtInNotice: {
		alignItems: "center",
		borderBottomColor: color.border,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		color: color.textMuted,
		display: "flex",
		flexShrink: 0,
		flexWrap: "wrap",
		fontSize: font.size_1,
		gap: controlSize._2,
		justifyContent: "space-between",
		paddingBlock: controlSize._2,
		paddingInline: controlSize._6,
		paddingRight: controlSize._12,
	},
	editorEmpty: {
		alignItems: "center",
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._3,
		justifyContent: "center",
		minWidth: 0,
		padding: controlSize._6,
		textAlign: "center",
	},
	emptyTitle: {
		color: color.textMain,
		fontSize: font.size_5,
		fontWeight: font.weight_6,
		letterSpacing: "-0.012em",
		margin: 0,
	},
	emptyHint: {
		color: color.textMuted,
		fontSize: font.size_2,
		margin: 0,
		maxWidth: "24rem",
	},
	error: {
		color: color.danger,
		fontSize: font.size_2,
		paddingInline: controlSize._4,
	},
});
