import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	radius,
	shadow,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	panel: {
		backgroundColor: color.transparent,
		display: "flex",
		flex: 1,
		flexDirection: "column",
		minHeight: controlSize._0,
		overflow: "hidden",
		width: "100%",
	},
	scopeRow: {
		alignItems: "center",
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "flex",
		gap: controlSize._1,
		paddingBlock: controlSize._1,
		paddingInline: controlSize._2,
	},
	scopeButton: {
		backgroundColor: color.transparent,
		borderColor: color.transparent,
		borderRadius: radius.sm,
		borderStyle: "solid",
		borderWidth: 1,
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		cursor: "pointer",
		fontSize: font.size_1,
		height: controlSize._6,
		paddingInline: controlSize._2,
		transitionDuration: motion.durationFast,
		transitionProperty: "background-color, border-color, color",
	},
	scopeButtonActive: {
		backgroundColor: color.surfaceControl,
		borderColor: color.border,
		color: color.textMain,
	},
	scopeDivider: {
		alignSelf: "stretch",
		borderLeftColor: color.borderSubtle,
		borderLeftStyle: "solid",
		borderLeftWidth: 1,
		marginBlock: controlSize._1,
	},
	body: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._2,
		minHeight: controlSize._0,
		padding: controlSize._3,
	},
	fieldLabel: {
		color: color.textMuted,
		fontSize: font.size_1,
	},
	editor: {
		backgroundColor: color.surfaceInset,
		borderColor: color.border,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textSoft,
		fontFamily: font.familyMono,
		fontSize: font.size_2,
		lineHeight: 1.5,
		flex: 1,
		minHeight: 180,
		outline: "none",
		padding: controlSize._2_5,
		resize: "none",
		":focus": {
			borderColor: color.borderStrong,
			boxShadow: shadow.focusRing,
		},
	},
});
