import * as stylex from "@octanejs/stylex";
import {
	breakpoint,
	color,
	controlSize,
	font,
	radius,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	settingsLayout: {
		display: "block",
		minWidth: controlSize._0,
	},
	modalScroller: {
		minWidth: controlSize._0,
		overflow: "visible",
	},
	settingsSection: {
		backgroundColor: color.surfaceWhite025,
		borderColor: color.border,
		borderRadius: radius.xl,
		borderStyle: "solid",
		borderWidth: 1,
		display: "flex",
		flexDirection: "column",
		gap: controlSize._4,
		padding: controlSize._4,
		scrollMarginTop: controlSize._5,
	},
	settingsCollection: {
		display: "block",
	},
	sectionIntro: {
		alignItems: {
			default: "flex-start",
			[breakpoint.tablet]: "center",
		},
		display: "flex",
		gap: controlSize._4,
		justifyContent: "space-between",
	},
	sectionIntroText: {
		minWidth: controlSize._0,
	},
	sectionTitle: {
		color: color.textMain,
		fontSize: font.size_5,
		fontWeight: font.weight_6,
		letterSpacing: "-0.006em",
		margin: controlSize._0,
	},
	sectionDescription: {
		color: color.textMuted,
		fontSize: font.size_2,
		lineHeight: 1.4,
		marginBlockEnd: controlSize._0,
		marginBlockStart: controlSize._1,
		maxWidth: "38rem",
	},
	sectionActions: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		gap: controlSize._2,
	},
	defaultSettingsGrid: {
		display: "grid",
		gridTemplateColumns: {
			default: "1fr",
			[breakpoint.standard]: "repeat(2, minmax(0, 1fr))",
		},
		gap: controlSize._2,
	},
	agentDefaultsControl: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._4,
	},
	agentProviderGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
		gap: controlSize._2,
	},
	agentProviderChoice: {
		alignItems: "center",
		display: "flex",
		backgroundColor: {
			default: color.surfaceWhite025,
			":hover": color.surfaceWhite06,
		},
		borderColor: color.border,
		borderRadius: radius.lg,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textSoft,
		fontSize: font.size_2,
		gap: controlSize._2,
		minHeight: controlSize._12,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._3,
		textAlign: "left",
		":disabled": {
			opacity: 0.45,
		},
	},
	agentProviderChoiceActive: {
		backgroundColor: color.surfaceWhite075,
		borderColor: color.borderStrong,
		color: color.textMain,
	},
	agentProviderIcon: {
		alignItems: "center",
		display: "inline-flex",
		flexShrink: 0,
		justifyContent: "center",
	},
	agentProviderText: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: controlSize._0,
	},
	agentProviderStatus: {
		color: color.textMuted,
		fontSize: font.size_1,
	},
	agentDefaultLabel: {
		color: color.textMuted,
		flexShrink: 0,
		fontSize: font.size_1,
	},
	settingField: {
		display: "flex",
		minWidth: controlSize._0,
		flexDirection: "column",
		gap: controlSize._1,
	},
	settingLabel: {
		color: color.textMuted,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
	},
	settingsDropdown: {
		backgroundColor: color.surfaceWhite025,
		backgroundImage: "none",
		borderColor: color.border,
		borderRadius: radius.lg,
		boxShadow: "none",
		fontSize: font.size_2,
		height: controlSize._8,
	},
	noShrink: {
		flexShrink: 0,
	},
	flexInput: {
		backgroundColor: color.surfaceWhite025,
		borderRadius: radius.lg,
		flex: 1,
	},
	content: {
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		gap: controlSize._3,
		marginInline: "auto",
		maxWidth: "46rem",
		paddingBlock: controlSize._5,
		paddingInline: controlSize._6,
		width: "100%",
	},
	cloneControls: {
		display: "flex",
		flexDirection: {
			default: "column",
			[breakpoint.tabletWide]: "row",
		},
		gap: controlSize._2,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		paddingBlock: controlSize._3,
	},
	cloneDirControls: {
		display: "flex",
		minWidth: controlSize._0,
		alignItems: "center",
		gap: controlSize._2,
		width: {
			default: "auto",
			[breakpoint.tabletWide]: "320px",
		},
	},
	repoList: {
		maxHeight: "320px",
		overflowY: "auto",
	},
	loadingState: {
		display: "flex",
		height: "6rem",
		alignItems: "center",
		justifyContent: "center",
		color: color.textMuted,
		fontSize: font.size_2,
	},
	accountLoadingState: {
		display: "flex",
		height: "7rem",
		alignItems: "center",
		justifyContent: "center",
		color: color.textMuted,
		fontSize: font.size_2,
	},
	githubAccountList: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._2,
	},
	githubRepoUnavailable: {
		alignItems: "center",
		color: color.textMuted,
		display: "flex",
		fontSize: font.size_2,
		height: "5rem",
		justifyContent: "center",
	},
});
