import * as stylex from "@octanejs/stylex";
import type { CSSProperties } from "react";
import {
	color,
	controlSize,
	font,
	layer,
	motion,
	palette,
	radius,
	runtimeColor,
	shadow,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	hidden: {
		display: "none",
	},
	attachments: {
		display: "flex",
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._2,
		overflowX: "auto",
		overflowY: "hidden",
		paddingBlock: "0.375rem",
		paddingInline: controlSize._3,
	},
	attachmentTile: {
		position: "relative",
		width: "3.5rem",
		height: "3.5rem",
		flexShrink: 0,
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
	},
	attachmentImage: {
		width: "100%",
		height: "100%",
		objectFit: "cover",
	},
	attachmentRemove: {
		position: "absolute",
		right: controlSize._1,
		top: controlSize._1,
		width: controlSize._5,
		height: controlSize._5,
		borderRadius: radius.pill,
		backgroundColor: color.surfaceBlack70,
		color: palette.white,
	},
	queueList: {
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		flexShrink: 0,
		maxHeight: "112px",
		overflowY: "auto",
		paddingBlock: controlSize._1,
		paddingInline: controlSize._1,
	},
	queueRow: {
		alignItems: "flex-start",
		borderRadius: radius.lg,
		display: "flex",
		gap: controlSize._2,
		paddingBlock: controlSize._1,
		paddingInline: controlSize._2,
		transitionProperty: "background-color",
		transitionDuration: motion.durationFast,
		":hover": {
			backgroundColor: color.backgroundRaised,
		},
	},
	queueIndex: {
		alignItems: "center",
		backgroundColor: color.surfaceSubtle,
		borderRadius: radius.pill,
		color: color.textMuted,
		display: "inline-flex",
		flexShrink: 0,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
		height: controlSize._5,
		justifyContent: "center",
		minWidth: controlSize._5,
	},
	queueEditRow: {
		display: "flex",
		flex: 1,
		alignItems: "center",
		gap: controlSize._1,
	},
	queueEditInput: {
		flex: 1,
		borderWidth: 0,
		borderRadius: radius.sm,
		backgroundColor: color.surfaceWhite06,
		color: color.textMain,
		fontSize: font.size_2_75,
		outline: "none",
		paddingBlock: "0.125rem",
		paddingInline: controlSize._1,
	},
	saveButton: {
		color: color.accent,
	},
	queueImage: {
		width: controlSize._5,
		height: controlSize._5,
		flexShrink: 0,
		borderRadius: radius.sm,
		objectFit: "cover",
	},
	queueText: {
		minWidth: controlSize._0,
		flex: 1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2_75,
	},
	queueActions: {
		display: "flex",
		flexShrink: 0,
		alignItems: "center",
		gap: "0.125rem",
	},
	floatingMenu: {
		position: "absolute",
		left: controlSize._0,
		right: controlSize._0,
		bottom: "100%",
		zIndex: layer.criticalOverlay,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		backgroundColor: color.backgroundPanel,
	},
	fileMenu: {
		maxHeight: "300px",
		overflowY: "auto",
		marginBottom: controlSize._1,
		borderRadius: controlSize._2,
		boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.6)",
	},
	menuHeader: {
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		color: color.textMuted,
		fontSize: font.size_1,
		fontWeight: font.weight_6,
		letterSpacing: "0.04em",
		paddingBlock: "0.375rem",
		paddingInline: controlSize._3,
	},
	fileMenuRow: {
		display: "flex",
		width: "100%",
		alignItems: "center",
		gap: controlSize._2,
		paddingBlock: "0.375rem",
		paddingInline: controlSize._3,
		textAlign: "left",
		transitionProperty: "background-color",
		transitionDuration: motion.durationFast,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	fileMenuRowActive: {
		backgroundColor: color.controlActive,
	},
	fileMenuIcon: {
		flexShrink: 0,
		color: color.textMuted,
		fontSize: font.size_2_75,
	},
	fileMenuName: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_2_75,
		fontWeight: font.weight_5,
	},
	fileMenuPath: {
		minWidth: controlSize._0,
		flex: 1,
		overflow: "hidden",
		textAlign: "right",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_1,
	},
	commandMenu: {
		maxHeight: "360px",
		overflow: "hidden",
		marginBottom: controlSize._2,
		borderRadius: radius.lg,
		boxShadow: shadow.modal,
	},
	commandList: {
		maxHeight: "280px",
		overflowY: "auto",
	},
	commandRow: {
		display: "flex",
		width: "100%",
		flexDirection: "column",
		gap: "0.125rem",
		paddingBlock: controlSize._2,
		paddingLeft: controlSize._3,
		paddingRight: controlSize._10,
		textAlign: "left",
		transitionProperty: "background-color",
		transitionDuration: motion.durationFast,
		transitionTimingFunction: motion.ease,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	commandRowActive: {
		backgroundColor: color.controlActive,
	},
	commandRowWrap: { position: "relative" },
	commandEdit: {
		position: "absolute",
		right: controlSize._2,
		top: "50%",
		transform: "translateY(-50%)",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: controlSize._6,
		height: controlSize._6,
		borderWidth: 0,
		borderRadius: radius.sm,
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceControl,
		},
		color: color.textMuted,
	},
	commandFooter: {
		display: "flex",
		justifyContent: "space-between",
		padding: controlSize._2,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: color.border,
	},
	menuAction: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._1,
		borderWidth: 0,
		borderRadius: radius.sm,
		padding: controlSize._1_5,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		color: color.textSoft,
		fontSize: font.size_1,
	},
	commandName: {
		color: color.textMain,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_3,
		fontWeight: font.weight_5,
	},
	commandTitleLine: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._2,
		minWidth: controlSize._0,
	},
	commandBadge: {
		backgroundColor: color.surfaceControl,
		borderColor: color.border,
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textMuted,
		fontSize: font.size_0_5,
		fontWeight: font.weight_5,
		paddingBlock: controlSize._0_25,
		paddingInline: controlSize._1,
		textTransform: "uppercase",
	},
	accentText: {
		color: "currentColor",
	},
	shrink: {
		flexShrink: 0,
	},
	providerConfigButton: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		backgroundImage: "none",
		borderColor: color.border,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 0,
		boxShadow: "none",
		boxSizing: "border-box",
		color: color.textSoft,
		display: "inline-flex",
		flexShrink: 1,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		gap: controlSize._1,
		height: controlSize._6,
		lineHeight: 1,
		maxWidth: "100%",
		minWidth: controlSize._0,
		paddingBlock: controlSize._0,
		paddingInline: controlSize._1,
		position: "relative",
		zIndex: layer.chrome,
	},
	providerConfigLabel: {
		minWidth: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	providerConfigChevron: {
		color: color.textMuted,
		flexShrink: 0,
		transitionDuration: motion.durationBase,
		transitionProperty: "transform",
	},
	providerConfigChevronOpen: {
		transform: "rotate(180deg)",
	},
	configControls: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		maxWidth: "100%",
		gap: controlSize._1,
		minWidth: controlSize._0,
	},
	workspaceControl: {
		display: "flex",
		justifyContent: "flex-end",
		marginLeft: "auto",
		minWidth: controlSize._0,
		maxWidth: "100%",
	},
	providerConfigMenu: {
		backgroundColor: color.backgroundPanel,
		borderRadius: radius.px10,
		borderColor: color.border,
		borderStyle: "solid",
		borderWidth: 1,
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		gap: controlSize._0_5,
		maxHeight: "min(320px, calc(100vh - 160px))",
		overflowY: "auto",
		padding: controlSize._1,
		width: "100%",
	},
	providerConfigAnchor: {
		position: "absolute",
		left: controlSize._3,
		bottom: "calc(100% + 6px)",
		zIndex: layer.composerPopover,
		width: "220px",
		maxWidth: "calc(100% - 24px)",
		pointerEvents: "auto",
	},
	providerConfigChoice: {
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		backgroundImage: "none",
		borderColor: color.transparent,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 0,
		boxShadow: "none",
		color: {
			default: color.textSoft,
			":hover": color.textMain,
		},
		display: "flex",
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		gap: controlSize._2,
		minHeight: controlSize._7,
		paddingBlock: controlSize._1,
		paddingInline: controlSize._2,
		textAlign: "left",
		transitionDuration: motion.durationBase,
		transitionProperty:
			"background-color, background-image, border-color, box-shadow, color",
		transitionTimingFunction: motion.ease,
	},
	providerConfigChoiceActive: {
		backgroundColor: color.controlActive,
		backgroundImage: "none",
		borderColor: color.border,
		boxShadow: "none",
		color: color.textMain,
	},
	modalBackdrop: {
		position: "absolute",
		inset: controlSize._0,
		zIndex: layer.modal,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: color.backgroundOverlay,
		backdropFilter: "blur(var(--inferay-glass-blur, 4px))",
	},
	modalBackdropButton: {
		position: "absolute",
		inset: controlSize._0,
		borderWidth: 0,
		backgroundColor: color.transparent,
		padding: controlSize._0,
	},
	modal: {
		position: "relative",
		display: "flex",
		width: "90%",
		maxWidth: "42rem",
		maxHeight: "80%",
		flexDirection: "column",
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.background,
	},
	modalHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._3,
	},
	modalTitle: {
		minWidth: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2_75,
		fontWeight: font.weight_5,
	},
	modalBody: {
		flex: 1,
		overflowY: "auto",
		color: color.textMain,
		fontSize: font.size_3,
		padding: controlSize._4,
	},
	modalState: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		paddingBlock: controlSize._8,
	},
	modalStateText: {
		color: color.textMuted,
		fontSize: font.size_2,
	},
	modalError: {
		color: color.danger,
		fontSize: font.size_2,
	},
	inputDock: {
		flexShrink: 0,
		paddingBottom: controlSize._2,
		paddingInline: controlSize._3,
		paddingTop: controlSize._1,
	},
	inputFrame: {
		display: "flex",
		flexDirection: "column",
		overflow: "visible",
		position: "relative",
		boxShadow: {
			default: "none",
			":focus-within": "none",
		},
		transitionProperty: "border-color, box-shadow, background-color",
		transitionDuration: motion.durationBase,
	},
	inputRow: {
		alignItems: "flex-end",
		display: "flex",
		gap: controlSize._1,
		paddingBlock: "0.375rem",
		paddingLeft: controlSize._1,
		paddingRight: controlSize._3,
	},
	inputActions: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		gap: controlSize._0_5,
	},
	noShrink: {
		flexShrink: 0,
	},
	voiceButtonListening: {
		backgroundColor: color.accentWash,
		color: color.textSoft,
	},
	voiceButtonError: {
		backgroundColor: color.warningWash,
		color: color.warning,
	},
	textAreaWrap: {
		flex: 1,
		minWidth: controlSize._0,
		overflow: "hidden",
		position: "relative",
	},
	highlightOverlay: {
		fontSize: font.size_4,
		left: controlSize._0,
		overflowWrap: "break-word",
		paddingRight: controlSize._8,
		pointerEvents: "none",
		position: "absolute",
		right: controlSize._0,
		top: controlSize._0,
		whiteSpace: "pre-wrap",
		wordBreak: "break-word",
	},
	textarea: {
		backgroundColor: color.transparent,
		borderWidth: 0,
		boxShadow: "none",
		cursor: "text",
		display: "block",
		fontSize: font.size_4,
		outline: "none",
		overflowY: "auto",
		paddingRight: controlSize._8,
		position: "relative",
		resize: "none",
		userSelect: "none",
		width: "100%",
	},
	pickerRow: {
		alignItems: "center",
		display: "flex",
		flexWrap: "wrap",
		gap: "0.375rem",
		minWidth: controlSize._0,
		paddingBottom: controlSize._1,
		paddingInline: controlSize._2,
		position: "relative",
		userSelect: "none",
		zIndex: layer.content,
	},
});

export function getChatComposerTextAreaWrapStyle(): CSSProperties {
	return { maxHeight: "120px" } as CSSProperties;
}

export function getChatComposerHighlightOverlayStyle(): CSSProperties {
	return {
		lineHeight: "20px",
		wordBreak: "break-word",
		overflowWrap: "break-word",
	} as CSSProperties;
}

export function getChatComposerTextareaStyle(
	color: CSSProperties["color"],
	WebkitTextFillColor: CSSProperties["WebkitTextFillColor"],
): CSSProperties {
	return {
		minHeight: "20px",
		color: color,
		caretColor: runtimeColor.textMain,
		WebkitTextFillColor: WebkitTextFillColor,
		lineHeight: "20px",
		wordBreak: "break-word",
		overflowWrap: "break-word",
	} as CSSProperties;
}
