import * as stylex from "@stylexjs/stylex";
import {
	color,
	controlSize,
	font,
	radius,
} from "../../../design-system/styles.stylex.ts";
export const styles = stylex.create({
	stack: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._8,
		minWidth: controlSize._0,
	},
	section: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._2,
		minWidth: controlSize._0,
		scrollMarginTop: controlSize._6,
	},
	sectionHead: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._4,
		justifyContent: "space-between",
		minWidth: controlSize._0,
	},
	sectionHeadText: {
		minWidth: controlSize._0,
	},
	sectionTitle: {
		color: color.textMain,
		fontSize: font.size_5,
		fontWeight: font.weight_6,
		letterSpacing: "-0.008em",
		margin: controlSize._0,
	},
	sectionDescription: {
		color: color.textMuted,
		fontSize: font.size_2,
		lineHeight: 1.5,
		marginBlockEnd: controlSize._0,
		marginBlockStart: controlSize._1,
		maxWidth: "34rem",
	},
	sectionAction: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		gap: controlSize._2,
	},
	sectionBody: {
		display: "flex",
		flexDirection: "column",
		minWidth: controlSize._0,
	},
	row: {
		alignItems: "center",
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: {
			default: 1,
			":last-child": 0,
		},
		display: "flex",
		gap: controlSize._4,
		justifyContent: "space-between",
		minHeight: controlSize._10,
		minWidth: controlSize._0,
		paddingBlock: controlSize._2,
	},
	rowText: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: controlSize._0,
	},
	rowLabel: {
		color: color.textSoft,
		fontSize: font.size_3,
		fontWeight: font.weight_5,
	},
	rowDescription: {
		color: color.textMuted,
		fontSize: font.size_1,
		lineHeight: 1.5,
	},
	rowControl: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		gap: controlSize._2,
		justifyContent: "flex-end",
		maxWidth: "100%",
	},
	rowControlFill: {
		flex: 1,
		justifyContent: "space-between",
		minWidth: controlSize._0,
	},
	empty: {
		color: color.textMuted,
		fontSize: font.size_2,
		paddingBlock: controlSize._3,
	},
	segmented: {
		backgroundColor: color.surfaceInset,
		borderColor: color.border,
		borderRadius: radius.lg,
		borderStyle: "solid",
		borderWidth: 1,
		display: "inline-flex",
		flexShrink: 0,
		gap: controlSize._0_5,
		maxWidth: "100%",
		padding: controlSize._0_5,
	},
	segment: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite06,
		},
		borderRadius: radius.md,
		borderWidth: 0,
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		display: "inline-flex",
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		gap: controlSize._1_5,
		justifyContent: "center",
		minHeight: controlSize._7,
		paddingInline: controlSize._2_5,
		whiteSpace: "nowrap",
		":disabled": {
			opacity: 0.4,
		},
	},
	segmentSelected: {
		backgroundColor: {
			default: color.backgroundRaised,
			":hover": color.backgroundRaised,
		},
		color: {
			default: color.textMain,
			":hover": color.textMain,
		},
	},
	segmentIcon: {
		alignItems: "center",
		display: "inline-flex",
		flexShrink: 0,
		justifyContent: "center",
	},
});
