import * as stylex from "@stylexjs/stylex";
import {
	color,
	font,
	radius,
} from "../../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	panel: { display: "flex", flexDirection: "column", gap: 12, minWidth: 0 },
	muted: { color: color.textMuted, fontSize: font.size_2 },
	table: { borderCollapse: "collapse", width: "100%", fontSize: font.size_3 },
	headCell: {
		color: color.textMuted,
		fontSize: font.size_2,
		fontWeight: 500,
		paddingBlock: 6,
		paddingInline: 8,
		textAlign: "left",
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
	},
	row: {
		cursor: "pointer",
		backgroundColor: { default: "transparent", ":hover": color.surfaceControl },
	},
	cell: {
		paddingBlock: 8,
		paddingInline: 8,
		verticalAlign: "top",
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
	},
	title: { color: color.textSoft, fontWeight: 500 },
	snippet: {
		color: color.textMuted,
		fontSize: font.size_2,
		marginTop: 2,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		maxWidth: 520,
	},
	stale: { opacity: 0.55 },
	tags: { display: "flex", flexWrap: "wrap", gap: 4 },
	tag: {
		backgroundColor: color.surfaceControl,
		borderRadius: radius.sm,
		borderWidth: 0,
		color: color.textSoft,
		cursor: "pointer",
		fontSize: font.size_1,
		paddingBlock: 1,
		paddingInline: 6,
	},
	badge: {
		borderColor: color.borderSubtle,
		borderRadius: radius.sm,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textMuted,
		fontSize: font.size_1,
		marginLeft: 6,
		paddingInline: 4,
	},
	note: { display: "flex", flexDirection: "column", gap: 10, maxWidth: 760 },
	body: {
		color: color.textSoft,
		fontSize: font.size_3,
		lineHeight: 1.55,
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
	},
	links: { display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" },
	form: { display: "flex", flexDirection: "column", gap: 8, maxWidth: 760 },
	textarea: {
		backgroundColor: color.surfaceInset,
		borderColor: color.borderSubtle,
		borderRadius: radius.sm,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textSoft,
		font: "inherit",
		fontSize: font.size_3,
		minHeight: 180,
		padding: 10,
		resize: "vertical",
	},
	error: { color: color.textMuted, fontSize: font.size_2 },
});
