import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	palette,
	radius,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	root: {
		backgroundColor: color.transparent,
		color: color.textMain,
		height: "100%",
		overflow: "hidden",
		paddingBlock: "3rem",
	},
	library: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._5,
		height: "100%",
		marginInline: "auto",
		maxWidth: 760,
		minWidth: controlSize._0,
		width: "min(760px, calc(100% - 4rem))",
	},
	topBar: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._4,
		justifyContent: "space-between",
	},
	title: {
		color: palette.white,
		fontSize: font.size_9,
		fontWeight: font.weight_6,
		letterSpacing: 0,
		lineHeight: 1,
		margin: controlSize._0,
	},
	searchBox: {
		alignItems: "center",
		backgroundColor: color.surfaceWhite12,
		borderColor: color.surfaceWhite18,
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		display: "flex",
		gap: controlSize._2,
		height: 34,
		paddingInline: controlSize._3,
		width: 216,
	},
	searchIcon: {
		color: color.textMuted,
		flexShrink: 0,
	},
	searchInput: {
		backgroundColor: color.transparent,
		borderWidth: 0,
		color: color.textMain,
		flex: 1,
		fontSize: font.size_2,
		minWidth: controlSize._0,
		outline: "none",
		padding: controlSize._0,
		"::placeholder": {
			color: color.textMuted,
		},
	},
	actionBar: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._2,
	},
	actionButton: {
		alignItems: "center",
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		display: "inline-flex",
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		gap: controlSize._1_5,
		height: controlSize._8,
		paddingInline: controlSize._3,
		transitionDuration: motion.durationFast,
		transitionProperty: "background-color, border-color, color",
	},
	actionButtonPrimary: {
		backgroundColor: palette.white,
		borderColor: palette.white,
		color: palette.black,
	},
	actionButtonDanger: {
		backgroundColor: color.transparent,
		borderColor: color.dangerBorder,
		color: color.danger,
	},
	actionButtonDisabled: {
		backgroundColor: color.surfaceWhite08,
		borderColor: color.surfaceWhite10,
		color: color.textMuted,
		cursor: "not-allowed",
	},
	selectionLabel: {
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		marginLeft: "auto",
	},
	table: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		minHeight: controlSize._0,
	},
	tableHeader: {
		alignItems: "center",
		color: color.textSoft,
		display: "grid",
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		gridTemplateColumns: "2.5rem minmax(0, 1fr) 10rem 8rem",
		height: controlSize._8,
		paddingInline: controlSize._1,
	},
	rows: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		minHeight: controlSize._0,
		overflowY: "auto",
		paddingBottom: controlSize._8,
		scrollbarWidth: "none",
		"::-webkit-scrollbar": {
			display: "none",
		},
	},
	row: {
		alignItems: "center",
		borderBottomColor: color.surfaceWhite06,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "grid",
		gap: controlSize._0,
		gridTemplateColumns: "2.5rem minmax(0, 1fr) 10rem 8rem",
		minHeight: 58,
		paddingInline: controlSize._1,
		transitionDuration: motion.durationFast,
		transitionProperty: "background-color, border-color",
	},
	rowIdle: {
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite05,
		},
	},
	rowSelected: {
		backgroundColor: color.surfaceWhite10,
		borderRadius: radius.md,
		borderBottomColor: color.transparent,
	},
	checkBox: {
		alignItems: "center",
		backgroundColor: color.surfaceWhite08,
		borderColor: color.surfaceWhite22,
		borderRadius: radius.sm,
		borderStyle: "solid",
		borderWidth: 1,
		color: palette.black,
		display: "flex",
		height: controlSize._4,
		justifyContent: "center",
		marginInline: "auto",
		padding: controlSize._0,
		width: controlSize._4,
	},
	checkBoxChecked: {
		backgroundColor: palette.white,
		borderColor: palette.white,
	},
	nameCell: {
		alignItems: "center",
		backgroundColor: color.transparent,
		borderWidth: 0,
		color: color.textMain,
		display: "flex",
		gap: controlSize._3,
		minWidth: controlSize._0,
		padding: controlSize._0,
		textAlign: "left",
	},
	thumbnailFrame: {
		alignItems: "center",
		backgroundColor: color.surfaceWhite10,
		borderColor: color.surfaceWhite18,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: 1,
		display: "flex",
		flexShrink: 0,
		height: 30,
		justifyContent: "center",
		overflow: "hidden",
		width: 30,
	},
	thumbnail: {
		height: "100%",
		objectFit: "cover",
		width: "100%",
	},
	fileName: {
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	metaCell: {
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	emptyState: {
		alignItems: "center",
		color: color.textMuted,
		display: "flex",
		fontSize: font.size_2,
		height: 180,
		justifyContent: "center",
		textAlign: "center",
	},
});
