import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	radius,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	projectButton: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		borderRadius: radius.md,
		borderWidth: 0,
		color: {
			default: color.textSoft,
			":hover": color.textMain,
		},
		cursor: "pointer",
		display: "inline-flex",
		flexShrink: 1,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
		gap: controlSize._1,
		height: controlSize._7,
		maxWidth: "12rem",
		minWidth: controlSize._0,
		overflow: "hidden",
		paddingBlock: controlSize._0,
		paddingInline: controlSize._2,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	projectButtonActive: {
		backgroundColor: color.controlActive,
		color: color.textMain,
	},
	headerDropdownButton: {
		"--dropdown-button-bg-color": "transparent",
		"--dropdown-button-bg-image": "none",
		"--dropdown-button-border-color": "transparent",
		"--dropdown-button-border-width": 0,
		"--dropdown-button-hover-bg-color": "transparent",
		"--dropdown-button-hover-bg-image": "none",
		"--dropdown-button-hover-shadow": "none",
		"--dropdown-button-open-bg-color": "transparent",
		"--dropdown-button-open-bg-image": "none",
		"--dropdown-button-open-border-color": "transparent",
		"--dropdown-button-open-shadow": "none",
		"--dropdown-button-shadow": "none",
		height: controlSize._5,
		borderRadius: radius.md,
		borderColor: color.transparent,
		borderWidth: 0,
		backgroundColor: {
			default: color.transparent,
			":hover": color.transparent,
		},
		backgroundImage: "none",
		boxShadow: "none",
		color: color.textSoft,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
		gap: controlSize._1,
		paddingInline: controlSize._1_5,
	},
	sessionLabel: {
		fontSize: font.size_1,
		maxWidth: "120px",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	sessionOption: {
		display: "flex",
		height: controlSize._12,
		alignItems: "center",
		gap: controlSize._2,
		paddingInline: controlSize._3,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
	},
	sessionOptionSelected: {
		backgroundColor: color.controlActive,
	},
	sessionOptionIcon: {
		display: "flex",
		flexShrink: 0,
		color: color.textSoft,
	},
	sessionOptionText: {
		display: "flex",
		minWidth: controlSize._0,
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		textAlign: "left",
	},
	sessionOptionRepo: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
	},
	sessionOptionTitle: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_1,
	},
});
