import * as stylex from "@stylexjs/stylex";
import {
	color,
	controlSize,
	font,
	layer,
	radius,
} from "../../../../design-system/styles.stylex.ts";
export const styles = stylex.create({
	bar: {
		alignItems: "stretch",
		backgroundColor: color.background,
		borderBottomColor: color.border,
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		boxSizing: "border-box",
		display: "flex",
		flexShrink: 0,
		height: controlSize._9,
		paddingLeft: 76,
		position: "relative",
		zIndex: layer.titlebar,
	},
	tabs: {
		display: "flex",
		flex: "0 1 auto",
		minWidth: controlSize._0,
		overflowX: "auto",
		overflowY: "hidden",
	},
	panelToggle: {
		alignItems: "center",
		alignSelf: "stretch",
		backgroundColor: color.transparent,
		color: {
			default: color.textMuted,
			":hover": color.textMain,
		},
		display: "flex",
		flexShrink: 0,
		justifyContent: "center",
		width: controlSize._10,
		":disabled": {
			cursor: "default",
			opacity: 0.45,
		},
	},
	workspaceSidebarToggle: {
		borderRightColor: color.border,
		borderRightStyle: "solid",
		borderRightWidth: 1,
	},
	panelControls: {
		display: "flex",
		flexShrink: 0,
		marginLeft: "auto",
	},
	changesSidebarToggle: {
		borderLeftColor: color.border,
		borderLeftStyle: "solid",
		borderLeftWidth: 1,
	},
	newMenuRoot: {
		display: "flex",
		flexShrink: 0,
		position: "relative",
	},
	newChat: {
		alignItems: "center",
		backgroundColor: color.transparent,
		borderRightColor: color.border,
		borderRightStyle: "solid",
		borderRightWidth: 1,
		color: {
			default: color.textSoft,
			":hover": color.textMain,
		},
		display: "flex",
		flexShrink: 0,
		fontSize: font.size_1,
		fontWeight: font.weight_6,
		gap: controlSize._1,
		paddingInline: controlSize._3,
	},
	newMenu: {
		borderRadius: radius.lg,
		display: "flex",
		flexDirection: "column",
		gap: controlSize._0_5,
		left: controlSize._1,
		padding: controlSize._1,
		position: "absolute",
		top: "calc(100% + 6px)",
		width: 228,
		zIndex: layer.dropdownPopover,
	},
	newMenuItem: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
			":focus-visible": color.controlHover,
		},
		borderRadius: radius.md,
		color: color.textMuted,
		display: "flex",
		gap: controlSize._2_5,
		minHeight: controlSize._12,
		outline: "none",
		paddingBlock: controlSize._2,
		paddingInline: controlSize._2_5,
		textAlign: "left",
		width: "100%",
	},
	newMenuCopy: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: controlSize._0,
	},
	newMenuLabel: {
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
	},
	newMenuDescription: {
		color: color.textFaint,
		fontSize: font.size_1,
		fontWeight: font.weightRegular,
	},
	tab: {
		borderLeftWidth: 1,
		borderLeftStyle: "solid",
		borderLeftColor: color.border,
		alignItems: "center",
		cursor: "grab",
		touchAction: "none",
		userSelect: "none",
		color: color.textMain,
		display: "flex",
		flexShrink: 0,
		fontSize: font.size_1,
		fontWeight: font.weight_6,
		gap: controlSize._1_5,
		maxWidth: 320,
		paddingInline: controlSize._3,
	},
	closeTab: {
		display: "flex",
		alignItems: "center",
		flexShrink: 0,
		color: { default: color.textFaint, ":hover": color.textMain },
		cursor: "pointer",
	},
	draggingTab: {
		cursor: "grabbing",
		opacity: 0.55,
	},
	dropBefore: {
		boxShadow: "inset 2px 0 0 currentColor",
	},
	dropAfter: {
		boxShadow: "inset -2px 0 0 currentColor",
	},
	tabLabel: {
		minWidth: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	emptyLabel: {
		alignItems: "center",
		color: color.textFaint,
		display: "flex",
		fontSize: font.size_1,
		paddingInline: controlSize._3,
	},
});
