import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	radius,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	accountCard: {
		alignItems: "center",
		backgroundColor: color.surfaceWhite025,
		borderColor: color.border,
		borderRadius: radius.lg,
		borderStyle: "solid",
		borderWidth: 1,
		display: "flex",
		gap: controlSize._3,
		minHeight: controlSize._16,
		padding: controlSize._3,
	},
	accountAvatar: {
		alignItems: "center",
		backgroundColor: color.controlActive,
		borderColor: color.borderStrong,
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textSoft,
		display: "flex",
		flexShrink: 0,
		fontSize: font.size_3,
		fontWeight: font.weight_6,
		height: controlSize._10,
		justifyContent: "center",
		overflow: "hidden",
		width: controlSize._10,
	},
	accountAvatarImage: {
		height: "100%",
		objectFit: "cover",
		width: "100%",
	},
	accountIdentity: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: controlSize._0,
	},
	accountNameRow: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._2,
		minWidth: controlSize._0,
	},
	accountName: {
		color: color.textMain,
		fontSize: font.size_3,
		fontWeight: font.weight_6,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	accountStatus: {
		alignItems: "center",
		borderColor: color.border,
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textMuted,
		display: "inline-flex",
		flexShrink: 0,
		fontSize: font.size_1,
		gap: controlSize._1,
		paddingBlock: controlSize._0_5,
		paddingInline: controlSize._1_5,
	},
	accountStatusDot: {
		backgroundColor: color.success,
		borderRadius: radius.pill,
		height: controlSize._1,
		width: controlSize._1,
	},
	accountHandle: {
		color: color.textMuted,
		fontSize: font.size_2,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	accountEmail: {
		color: color.textFaint,
		fontSize: font.size_1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	rowText: {
		minWidth: controlSize._0,
		flex: 1,
	},
	repoRow: {
		display: "flex",
		minHeight: "64px",
		alignItems: "center",
		gap: controlSize._3,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		paddingBlock: controlSize._3,
		paddingInline: controlSize._0,
	},
	inlineRow: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._2,
	},
	repoName: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_5,
	},
	repoDescription: {
		marginTop: controlSize._1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_0_5,
	},
	privatePill: {
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.pill,
		color: color.textMuted,
		fontSize: font.size_0,
		paddingBlock: "0.125rem",
		paddingInline: "0.375rem",
	},
	externalLink: {
		display: "flex",
		width: controlSize._7,
		height: controlSize._7,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.md,
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		backgroundColor: {
			default: color.transparent,
			":hover": color.backgroundRaised,
		},
		transitionProperty: "background-color, color",
		transitionDuration: motion.durationFast,
	},
});
