import * as stylex from "@stylexjs/stylex";
import {
	color,
	controlSize,
	font,
	motion,
	radius,
} from "../../../../design-system/styles.stylex.ts";
export const styles = stylex.create({
	row: {
		alignItems: "center",
		borderBottomColor: color.borderSubtle,
		borderBottomStyle: "solid",
		borderBottomWidth: {
			default: 1,
			":last-child": 0,
		},
		display: "flex",
		gap: controlSize._3,
		minHeight: controlSize._12,
		minWidth: controlSize._0,
		paddingBlock: controlSize._2,
	},
	accountAvatar: {
		alignItems: "center",
		backgroundColor: color.surfaceWhite06,
		borderRadius: radius.pill,
		color: color.textSoft,
		display: "flex",
		flexShrink: 0,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		height: controlSize._8,
		justifyContent: "center",
		overflow: "hidden",
		width: controlSize._8,
	},
	accountAvatarImage: {
		height: "100%",
		objectFit: "cover",
		width: "100%",
	},
	rowText: {
		display: "flex",
		flex: 1,
		flexDirection: "column",
		gap: controlSize._0_5,
		minWidth: controlSize._0,
	},
	rowTitleLine: {
		alignItems: "center",
		display: "flex",
		gap: controlSize._2,
		minWidth: controlSize._0,
	},
	accountName: {
		color: color.textMain,
		fontSize: font.size_3,
		fontWeight: font.weight_5,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	accountStatus: {
		alignItems: "center",
		color: color.textMuted,
		display: "inline-flex",
		flexShrink: 0,
		fontSize: font.size_1,
		gap: controlSize._1,
	},
	accountStatusDot: {
		backgroundColor: color.success,
		borderRadius: radius.pill,
		height: controlSize._1,
		width: controlSize._1,
	},
	subtleText: {
		color: color.textMuted,
		fontSize: font.size_1,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	repoName: {
		color: color.textSoft,
		fontSize: font.size_3,
		fontWeight: font.weight_5,
		margin: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	repoDescription: {
		color: color.textMuted,
		fontSize: font.size_1,
		margin: controlSize._0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	privatePill: {
		borderColor: color.border,
		borderRadius: radius.pill,
		borderStyle: "solid",
		borderWidth: 1,
		color: color.textMuted,
		flexShrink: 0,
		fontSize: font.size_0_5,
		paddingBlock: "0.125rem",
		paddingInline: "0.375rem",
	},
	externalLink: {
		alignItems: "center",
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite06,
		},
		borderRadius: radius.md,
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		display: "flex",
		flexShrink: 0,
		height: controlSize._7,
		justifyContent: "center",
		transitionDuration: motion.durationFast,
		transitionProperty: "background-color, color",
		width: controlSize._7,
	},
	noShrink: {
		flexShrink: 0,
	},
});
