import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	layer,
	motion,
	radius,
} from "../../../../design-system/styles.stylex.ts";

export const EASING = "cubic-bezier(.22,.82,.2,1)";

export const styles = stylex.create({
	root: {
		position: "relative",
		height: "100%",
		overflow: "hidden",
		backgroundColor: color.background,
		color: color.textMain,
		fontFamily:
			"ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
		WebkitFontSmoothing: "antialiased",
	},
	gridBackdrop: {
		backgroundImage:
			"linear-gradient(to right, var(--color-inferay-white) 1px, transparent 1px), linear-gradient(to bottom, var(--color-inferay-white) 1px, transparent 1px)",
		backgroundSize: "42px 42px",
		inset: controlSize._0,
		maskImage:
			"radial-gradient(ellipse 82% 68% at 50% 42%, black 15%, transparent 78%)",
		pointerEvents: "none",
		position: "absolute",
		transitionDuration: motion.durationLong,
		transitionProperty: "opacity",
		transitionTimingFunction: EASING,
	},
	gridBackdropVisible: {
		opacity: 0.09,
	},
	gridBackdropHidden: {
		opacity: 0,
	},
	bottomFade: {
		background:
			"linear-gradient(to top, var(--color-inferay-black), transparent)",
		position: "absolute",
		insetInline: controlSize._0,
		bottom: controlSize._0,
		height: "50%",
		pointerEvents: "none",
	},
	stepSurface: {
		alignItems: "center",
		display: "flex",
		inset: controlSize._0,
		justifyContent: "center",
		position: "absolute",
		transitionProperty: "filter, opacity, transform",
		transitionTimingFunction: EASING,
		zIndex: layer.control,
	},
	stepSurfaceStandard: {
		transitionDuration: motion.durationLong,
	},
	stepSurfaceSlow: {
		transitionDuration: motion.durationSecond,
	},
	stepActive: {
		filter: "blur(0)",
		opacity: 1,
		pointerEvents: "auto",
		transform: "translate3d(0, 0, 0) scale(1)",
	},
	introBefore: {
		opacity: 0,
		pointerEvents: "none",
		transform: "translate3d(40vw, 0, 0)",
	},
	introAfter: {
		opacity: 0,
		pointerEvents: "none",
		transform: "translate3d(-40vw, 0, 0)",
	},
	forwardBefore: {
		filter: "blur(4px)",
		opacity: 0,
		pointerEvents: "none",
		transform: "translate3d(40vw, 8vh, 0)",
	},
	forwardAfter: {
		filter: "blur(4px)",
		opacity: 0,
		pointerEvents: "none",
		transform: "translate3d(-40vw, 8vh, 0)",
	},
	projectsAfter: {
		filter: "blur(4px)",
		opacity: 0,
		pointerEvents: "none",
		transform: "translate3d(-18vw, -16vh, 0) scale(1.08)",
	},
	introStack: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		textAlign: "center",
	},
	logoFrame: {
		display: "flex",
		width: "72px",
		height: "72px",
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		marginBottom: "1.75rem",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._4,
		backgroundColor: color.backgroundRaised,
		boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.4)",
	},
	logo: {
		width: "72px",
		height: "72px",
		borderRadius: controlSize._4,
		objectFit: "cover",
	},
	heroTitle: {
		color: color.textMain,
		fontSize: font.size_10,
		fontWeight: font.weight_6,
		letterSpacing: 0,
		lineHeight: 1.15,
	},
	heroText: {
		maxWidth: "28rem",
		marginTop: controlSize._4,
		color: color.textMuted,
		fontSize: font.size_4,
		fontWeight: font.weight_5,
		lineHeight: 1.85,
	},
	primaryActions: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._3,
		marginTop: controlSize._7,
	},
	skipButton: {
		marginTop: controlSize._5,
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		fontSize: font.size_2_75,
		transitionProperty: "color",
		transitionDuration: motion.durationFast,
	},
	stepPanel: {
		display: "flex",
		width: "520px",
		maxWidth: "100%",
		flexDirection: "column",
		paddingInline: controlSize._6,
	},
	projectPanel: {
		display: "flex",
		width: "540px",
		maxWidth: "100%",
		flexDirection: "column",
		paddingInline: controlSize._6,
	},
	centerText: {
		textAlign: "center",
	},
	stepTitle: {
		color: color.textMain,
		fontSize: font.size_9,
		fontWeight: font.weight_6,
		letterSpacing: 0,
	},
	stepDescription: {
		maxWidth: "28rem",
		marginInline: "auto",
		marginTop: controlSize._3,
		color: color.textMuted,
		fontSize: font.size_3,
		lineHeight: 1.85,
	},
	inlineCodeText: {
		color: color.textSoft,
		fontFamily: "var(--font-diff)",
	},
	stepContent: {
		marginTop: controlSize._7,
	},
	loadingState: {
		display: "flex",
		height: "5rem",
		alignItems: "center",
		justifyContent: "center",
		color: color.textMuted,
		fontSize: font.size_3,
	},
	spinIcon: {
		marginRight: "0.625rem",
		animationName: stylex.keyframes({
			to: {
				transform: "rotate(360deg)",
			},
		}),
		animationDuration: motion.durationLongest,
		animationIterationCount: "infinite",
		animationTimingFunction: "linear",
	},
	accountList: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._2,
	},
	accountRow: {
		display: "flex",
		alignItems: "center",
		gap: controlSize._3,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.backgroundRaised,
		padding: controlSize._3,
	},
	avatarFrame: {
		display: "flex",
		width: "2.5rem",
		height: "2.5rem",
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.pill,
		backgroundColor: color.controlActive,
	},
	avatar: {
		width: "100%",
		height: "100%",
		objectFit: "cover",
	},
	mutedIcon: {
		color: color.textMuted,
	},
	shrink: {
		flexShrink: 0,
	},
	rowText: {
		minWidth: controlSize._0,
		flex: 1,
	},
	accountName: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_4,
		fontWeight: font.weight_5,
	},
	accountMeta: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_2_75,
	},
	noticeCard: {
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.backgroundRaised,
		padding: controlSize._5,
		textAlign: "center",
	},
	noticeIconBox: {
		display: "flex",
		width: "2.5rem",
		height: "2.5rem",
		alignItems: "center",
		justifyContent: "center",
		marginInline: "auto",
		marginBottom: controlSize._4,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.background,
		color: color.textMuted,
	},
	noticeTitle: {
		color: color.textMain,
		fontSize: font.size_3,
		fontWeight: font.weight_5,
	},
	noticeText: {
		marginTop: controlSize._1,
		color: color.textMuted,
		fontSize: font.size_2_75,
	},
	noticeActions: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._2,
		marginTop: controlSize._4,
	},
	actionCards: {
		display: "grid",
		gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
		gap: controlSize._3,
		marginTop: controlSize._7,
	},
	projectActionCard: {
		display: "flex",
		cursor: "pointer",
		flexDirection: "column",
		alignItems: "flex-start",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: {
			default: color.backgroundRaised,
			":hover": color.controlActive,
		},
		padding: controlSize._4,
		textAlign: "left",
		transitionProperty: "background-color, opacity",
		transitionDuration: motion.durationFast,
		":disabled": {
			cursor: "default",
			opacity: 0.7,
		},
	},
	projectActionIcon: {
		display: "flex",
		width: "2.5rem",
		height: "2.5rem",
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.background,
		color: color.textSoft,
	},
	projectActionTitle: {
		marginTop: controlSize._4,
		color: color.textMain,
		fontSize: font.size_4,
		fontWeight: font.weight_5,
	},
	projectActionText: {
		marginTop: controlSize._1,
		color: color.textMuted,
		fontSize: font.size_2_75,
		lineHeight: 1.6,
	},
	projectListSection: {
		minHeight: controlSize._0,
		flex: 1,
		marginTop: controlSize._6,
	},
	listMeta: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: controlSize._2,
		color: color.textMuted,
		fontSize: font.size_2_75,
	},
	projectList: {
		maxHeight: "240px",
		overflowY: "auto",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: controlSize._2,
		backgroundColor: color.backgroundRaised,
		scrollbarWidth: "none",
	},
	localFolderRow: {
		display: "flex",
		height: "2.5rem",
		alignItems: "center",
		gap: controlSize._2,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		paddingInline: controlSize._3,
	},
	repoRow: {
		display: "flex",
		width: "100%",
		alignItems: "center",
		gap: "0.625rem",
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._3,
		textAlign: "left",
		transitionProperty: "background-color",
		transitionDuration: motion.durationFast,
		backgroundColor: {
			default: color.transparent,
			":hover": color.surfaceWhite04,
		},
	},
	repoRowSelected: {
		backgroundColor: color.surfaceWhite05,
	},
	repoCheck: {
		display: "flex",
		width: controlSize._4,
		height: controlSize._4,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.sm,
		backgroundColor: color.background,
		transitionProperty: "background-color, border-color, color",
		transitionDuration: motion.durationFast,
	},
	repoCheckSelected: {
		borderColor: color.textMain,
		backgroundColor: color.textMain,
		color: color.background,
	},
	repoName: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMain,
		fontSize: font.size_2_75,
		fontWeight: font.weight_5,
	},
	repoDescription: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		color: color.textMuted,
		fontSize: font.size_2,
	},
	repoMeta: {
		display: "flex",
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._2,
	},
	repoLanguage: {
		color: color.textMuted,
		fontSize: font.size_2,
	},
	privatePill: {
		borderRadius: radius.sm,
		backgroundColor: color.controlActive,
		color: color.textMuted,
		fontSize: font.size_1,
		paddingBlock: "0.125rem",
		paddingInline: controlSize._1,
	},
	projectEmpty: {
		display: "flex",
		height: "7rem",
		alignItems: "center",
		justifyContent: "center",
		color: color.textMuted,
		fontSize: font.size_2_75,
		lineHeight: 1.6,
		textAlign: "center",
	},
});
export { routeStyles } from "../OnboardingRoute/styles.ts";
