import * as stylex from "@octanejs/stylex";
import {
	color,
	controlSize,
	font,
	radius,
} from "../../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	root: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._3,
	},
	plainText: {
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
		color: color.textSoft,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_2,
	},
	mermaidBox: {
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.md,
		backgroundColor: color.backgroundRaised,
		padding: controlSize._3,
	},
	mermaidRender: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		overflowX: "auto",
		padding: controlSize._4,
	},
	errorPre: {
		color: color.danger,
		fontSize: font.size_2,
		whiteSpace: "pre-wrap",
	},
	image: {
		display: "inline-block",
		maxWidth: "100%",
		borderRadius: radius.md,
		marginBlock: controlSize._1,
	},
	link: {
		color: color.accent,
		textDecorationLine: "underline",
		textDecorationColor: color.accentBorder,
		textUnderlineOffset: "2px",
		":hover": {
			textDecorationColor: color.accent,
		},
	},
	inlineCode: {
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.accentBorder,
		borderRadius: radius.sm,
		backgroundColor: color.accentWash,
		color: color.accent,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_2,
		paddingBlock: "0.125rem",
		paddingInline: "0.375rem",
	},
	strongBold: {
		color: color.textMain,
		fontWeight: font.weightBold,
	},
	strong: {
		color: color.textMain,
		fontWeight: font.weight_6,
	},
	italic: {
		color: color.textSoft,
		fontStyle: "italic",
	},
	deleted: {
		color: color.textMuted,
		textDecorationLine: "line-through",
	},
	heading: {
		color: color.textMain,
		fontWeight: font.weight_6,
	},
	heading1: {
		marginTop: controlSize._6,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		fontSize: font.size_7,
		fontWeight: font.weightBold,
		paddingBottom: controlSize._2,
	},
	heading2: {
		marginTop: controlSize._5,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.border,
		fontSize: font.size_5_5,
		paddingBottom: "0.375rem",
	},
	heading3: {
		marginTop: controlSize._4,
		fontSize: font.size_4,
	},
	heading4: {
		marginTop: controlSize._3,
		fontSize: font.size_3,
	},
	heading5: {
		marginTop: controlSize._2,
		fontSize: font.size_2_75,
	},
	heading6: {
		marginTop: controlSize._2,
		color: color.textSoft,
		fontSize: font.size_2,
		letterSpacing: "0.04em",
		textTransform: "uppercase",
	},
	listItem: {
		color: color.textSoft,
		fontSize: font.size_2_75,
		lineHeight: 1.6,
	},
	checkSlot: {
		display: "inline-flex",
		marginRight: "0.375rem",
	},
	checkOn: {
		display: "inline-flex",
		width: "0.875rem",
		height: "0.875rem",
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.accentBorder,
		borderRadius: radius.sm,
		backgroundColor: color.accentWash,
		color: color.accent,
		fontSize: font.size_0_5,
	},
	checkOff: {
		display: "inline-flex",
		width: "0.875rem",
		height: "0.875rem",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.sm,
	},
	nestedList: {
		display: "flex",
		flexDirection: "column",
		gap: "0.125rem",
		listStyleType: "disc",
		marginTop: controlSize._1,
		paddingLeft: controlSize._5,
	},
	codeBlock: {
		position: "relative",
	},
	codeLang: {
		position: "absolute",
		top: "0.375rem",
		right: controlSize._2,
		color: color.surfaceWhite40,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_0_5,
		letterSpacing: "0.08em",
		textTransform: "uppercase",
	},
	pre: {
		overflowX: "auto",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.accentBorder,
		borderRadius: radius.md,
		backgroundColor: color.backgroundRaised,
		padding: controlSize._3,
	},
	codeText: {
		color: color.textSoft,
		fontFamily: "var(--font-diff)",
		fontSize: font.size_2,
		lineHeight: "18px",
		whiteSpace: "pre",
	},
	blockquote: {
		borderLeftWidth: 2,
		borderLeftStyle: "solid",
		borderLeftColor: color.accentBorder,
		paddingBlock: "0.125rem",
		paddingLeft: controlSize._4,
	},
	hr: {
		borderColor: color.border,
		marginBlock: controlSize._4,
	},
	tableWrap: {
		overflowX: "auto",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.accentBorder,
		borderRadius: radius.md,
	},
	table: {
		width: "100%",
		fontSize: font.size_2,
	},
	tableHeadRow: {
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.accentBorder,
		backgroundColor: color.accentWash,
	},
	tableHeadCell: {
		color: color.textMain,
		fontWeight: font.weight_5,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._3,
		textAlign: "left",
		whiteSpace: "nowrap",
	},
	tableRow: {
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: color.surfaceWhite04,
	},
	tableCell: {
		color: color.textSoft,
		paddingBlock: "0.375rem",
		paddingInline: controlSize._3,
	},
	checklist: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._1,
		paddingLeft: controlSize._1,
	},
	unorderedList: {
		display: "flex",
		flexDirection: "column",
		gap: "0.125rem",
		listStyleType: "disc",
		paddingLeft: controlSize._5,
	},
	orderedList: {
		display: "flex",
		flexDirection: "column",
		gap: "0.125rem",
		listStyleType: "decimal",
		paddingLeft: controlSize._5,
	},
	paragraph: {
		color: color.textSoft,
		fontSize: font.size_2_75,
		lineHeight: 1.6,
	},
});
