import * as stylex from "@octanejs/stylex";

import {
	color,
	controlSize,
	font,
	layer,
	motion,
	radius,
	shadow,
} from "../../../../design-system/styles.stylex.ts";

export const styles = stylex.create({
	srStatus: {
		position: "absolute",
		width: "1px",
		height: "1px",
		overflow: "hidden",
		borderWidth: 0,
		clip: "rect(0 0 0 0)",
		margin: "-1px",
		padding: 0,
		whiteSpace: "nowrap",
	},

	viewerPanel: {
		position: "relative",
		display: "flex",
		width: "100%",
		height: "100%",
		minWidth: controlSize._0,
		minHeight: controlSize._0,
		flexDirection: "column",
		backgroundColor: color.transparent,
		overflow: "hidden",
	},
	viewerHeader: {
		display: "flex",
		height: controlSize._8,
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._2,
		paddingInline: controlSize._3,
	},
	viewerHeaderFloating: {
		position: "absolute",
		bottom: controlSize._2,
		left: "50%",
		zIndex: layer.dropdown,
		width: "auto",
		maxWidth: "calc(100% - 1.5rem)",
		height: controlSize._10,
		boxSizing: "border-box",
		gap: controlSize._2,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.xl,
		backgroundColor: color.backgroundPanel,
		boxShadow: "0 8px 24px rgba(0,0,0,.28)",
		paddingInline: controlSize._3,
		transform: "translateX(-50%)",
	},
	viewerFloatingScrim: {
		position: "absolute",
		left: controlSize._0,
		right: controlSize._0,
		bottom: controlSize._0,
		zIndex: layer.content,
		height: 80,
		pointerEvents: "none",
		backgroundImage:
			"linear-gradient(to top, var(--inferay-surface-base, var(--color-inferay-black)) 0px, var(--inferay-surface-base, var(--color-inferay-black)) 24px, transparent 80px)",
	},
	viewerFloatingScrimAboveContent: {
		zIndex: layer.control,
	},
	viewerFloatingFile: {
		alignItems: "center",
		display: "flex",
		flexShrink: 1,
		gap: controlSize._1_5,
		minWidth: controlSize._0,
	},
	viewerFloatingPath: {
		minWidth: controlSize._0,
		overflow: "hidden",
		fontFamily: font.familyDiff,
		fontSize: font.size_1,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	viewerFileName: {
		color: color.textMain,
		fontWeight: font.weightBold,
	},
	viewerStats: {
		display: "flex",
		flexShrink: 0,
		gap: controlSize._1_5,
		fontFamily: font.familyDiff,
		fontSize: font.size_1,
		fontVariantNumeric: "tabular-nums",
	},
	viewerFloatingDivider: {
		backgroundColor: color.border,
		flexShrink: 0,
		height: controlSize._5,
		width: 1,
	},
	graphSyncActions: {
		display: "flex",
		flexShrink: 0,
		alignItems: "center",
		gap: controlSize._0_5,
		marginLeft: "auto",
	},
	graphSyncButton: {
		display: "flex",
		minWidth: controlSize._10,
		height: controlSize._8,
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: controlSize._0_5,
		paddingInline: controlSize._1,
		borderRadius: radius.sm,
		fontSize: font.size_1,
		fontWeight: font.weight_5,
		lineHeight: 1,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		color: {
			default: color.textMuted,
			":hover": color.textSoft,
		},
		":disabled": {
			opacity: 0.45,
		},
	},
	graphPushIcon: {
		transform: "rotate(180deg)",
	},
	viewerModes: {
		position: "relative",
		isolation: "isolate",
		display: "flex",
		height: controlSize._5,
		flexShrink: 0,
		alignItems: "center",
		backgroundColor: color.transparent,
	},
	viewerModeButton: {
		position: "relative",
		zIndex: layer.content,
		display: "flex",
		width: controlSize._6,
		height: "100%",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: radius.sm,
		backgroundColor: color.transparent,
		color: color.textMuted,
		transitionProperty: "color",
		transitionDuration: motion.durationFast,
	},
	viewerModeButtonActive: {
		backgroundColor: color.transparent,
		color: color.textMain,
	},
	viewerAdded: { color: color.diffAdded },
	viewerRemoved: { color: color.diffRemoved },
	viewerClose: {
		display: "flex",
		width: controlSize._5,
		height: controlSize._5,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: { default: color.transparent, ":hover": color.dangerWash },
		color: { default: color.textMuted, ":hover": color.danger },
	},
	viewerBody: {
		position: "relative",
		minHeight: controlSize._0,
		flex: 1,
		overflow: "hidden",
	},
	viewerBodyAboveScrim: {
		zIndex: layer.chrome,
	},
	refActionOverlay: {
		position: "absolute",
		zIndex: layer.dropdown,
		inset: controlSize._0,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: color.backgroundOverlay,
		padding: controlSize._4,
	},
	refActionDialog: {
		display: "flex",
		width: "min(32rem, 100%)",
		maxHeight: "calc(100% - 2rem)",
		flexDirection: "column",
		gap: controlSize._3,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.borderStrong,
		borderRadius: radius.md,
		backgroundColor: color.backgroundRaised,
		overflow: "hidden",
		padding: controlSize._4,
	},
	refActionTitle: {
		color: color.textMain,
		fontSize: font.size_4,
	},
	refActionCopy: {
		color: color.textSoft,
		fontSize: font.size_2_75,
		lineHeight: 1.5,
	},
	refActionError: {
		color: color.danger,
		fontSize: font.size_2,
		lineHeight: 1.5,
	},
	rebasePlan: {
		display: "flex",
		minHeight: controlSize._0,
		flexDirection: "column",
		gap: controlSize._1,
		overflowY: "auto",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.sm,
		backgroundColor: color.background,
		padding: controlSize._1,
	},
	rebasePlanRow: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._1,
		borderRadius: radius.sm,
		backgroundColor: color.surfaceWhite02,
		cursor: "grab",
		padding: controlSize._1,
	},
	rebasePlanControls: {
		display: "flex",
		minWidth: controlSize._0,
		alignItems: "center",
		gap: controlSize._1,
	},
	rebaseActionSelect: {
		height: controlSize._6,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.sm,
		backgroundColor: color.surfaceControl,
		color: color.textSoft,
		fontSize: font.size_2,
		paddingInline: controlSize._1,
	},
	rebaseMoveButton: {
		display: "flex",
		width: controlSize._5,
		height: controlSize._5,
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		borderRadius: radius.sm,
		backgroundColor: {
			default: color.transparent,
			":hover": color.controlHover,
		},
		color: color.textMuted,
		fontSize: font.size_2,
		":disabled": { opacity: 0.3 },
	},
	rebaseSha: {
		flexShrink: 0,
		color: color.textMuted,
		fontFamily: font.familyMono,
		fontSize: font.size_1,
	},
	rebaseSubject: {
		minWidth: controlSize._0,
		flex: 1,
		overflow: "hidden",
		color: color.textSoft,
		fontSize: font.size_2,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	graphActionField: {
		display: "flex",
		flexDirection: "column",
		gap: controlSize._1_5,
		color: color.textSoft,
		fontSize: font.size_2,
	},
	graphActionInput: {
		width: "100%",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: {
			default: color.border,
			":focus": color.accentBorder,
		},
		borderRadius: radius.sm,
		outline: "none",
		resize: "vertical",
		backgroundColor: color.background,
		color: color.textMain,
		fontFamily: font.familyDiff,
		fontSize: font.size_2_75,
		paddingBlock: controlSize._2,
		paddingInline: controlSize._2,
	},
	refActionButtons: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "flex-end",
		gap: controlSize._2,
	},
	refActionSecondary: {
		height: controlSize._7,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.border,
		borderRadius: radius.sm,
		backgroundColor: {
			default: color.surfaceControl,
			":hover": color.controlHover,
		},
		color: color.textSoft,
		fontSize: font.size_2,
		paddingInline: controlSize._3,
	},
	refActionPrimary: {
		height: controlSize._7,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.accentBorder,
		borderRadius: radius.sm,
		backgroundColor: {
			default: color.controlActive,
			":hover": color.accentWash,
		},
		color: color.textMain,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		paddingInline: controlSize._3,
	},
	graphActionDanger: {
		height: controlSize._7,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.danger,
		borderRadius: radius.sm,
		backgroundColor: {
			default: color.dangerWash,
			":hover": color.dangerWash,
		},
		color: color.danger,
		fontSize: font.size_2,
		fontWeight: font.weight_6,
		paddingInline: controlSize._3,
	},
	repositoryOperationBar: {
		position: "absolute",
		zIndex: layer.dropdown,
		left: controlSize._3,
		right: controlSize._3,
		bottom: controlSize._3,
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: controlSize._3,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: color.warning,
		borderRadius: radius.md,
		backgroundColor: color.backgroundRaised,
		boxShadow: shadow.popover,
		padding: controlSize._3,
	},
	repositoryOperationCopy: {
		display: "flex",
		minWidth: controlSize._0,
		flexDirection: "column",
		gap: controlSize._1,
		color: color.textSoft,
		fontSize: font.size_2,
		textTransform: "capitalize",
	},
	viewerEmpty: {
		display: "flex",
		height: "100%",
		alignItems: "center",
		justifyContent: "center",
		color: color.textMuted,
		fontSize: font.size_2,
	},
});
